import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { getUser, allow } from '../../../../lib/auth.js';
import { readState, orderTotal, orderCost } from '../../../../lib/store.js';

function inPeriod(date,period){const d=new Date(date),n=new Date();if(period==='daily')return d.toDateString()===n.toDateString();if(period==='monthly')return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth();return d.getFullYear()===n.getFullYear()}
function addSheet(wb,name,rows,widths=[]){const ws=XLSX.utils.json_to_sheet(rows);if(widths.length)ws['!cols']=widths.map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,name)}
export async function GET(request){const user=await getUser();if(!allow(user,'manager'))return NextResponse.json({error:'Manager only.'},{status:403});const period=new URL(request.url).searchParams.get('period')||'daily';const s=await readState();const orders=s.orders.filter(o=>o.status==='paid'&&inPeriod(o.paid_at||o.created_at,period));const expenses=s.expenses.filter(e=>inPeriod(e.date||e.created_at,period));const sales=orders.reduce((a,o)=>a+orderTotal(o,s.settings.exchange_rate).total_equivalent_cents/100,0);const cogs=orders.reduce((a,o)=>a+orderCost(s,o),0);const exp=expenses.reduce((a,e)=>a+Number(e.amount||0),0);const wb=XLSX.utils.book_new();
addSheet(wb,'Summary',[{Period:period,Revenue_USD:sales,Orders:orders.length,Average_Order_USD:orders.length?sales/orders.length:0,COGS_USD:cogs,Gross_Profit_USD:sales-cogs,Expenses_USD:exp,Net_Profit_USD:sales-cogs-exp,Gross_Margin_Percent:sales?((sales-cogs)/sales)*100:0,Inventory_Value_USD:s.inventory.reduce((a,i)=>a+Number(i.quantity||0)*Number(i.unit_cost||0),0)}],[22,18,14,20,16,20,18,18,22,22]);
addSheet(wb,'Orders',orders.map(o=>{const t=orderTotal(o,s.settings.exchange_rate),p=o.payments?.[0]||{};return {Order:o.number,Date:o.paid_at||o.created_at,Type:o.type,Table:s.tables.find(t=>t.id===o.table_id)?.name||'',Staff:o.created_by_name,Cashier:p.cashier||'',Items:o.lines.reduce((a,l)=>a+l.quantity,0),Sales_USD:t.total_equivalent_cents/100,COGS_USD:orderCost(s,o),Gross_Profit_USD:t.total_equivalent_cents/100-orderCost(s,o),Paid_USD:(p.usd_cents||0)/100,Paid_LBP:p.lbp||0,Exchange_Rate:p.rate||s.settings.exchange_rate}}),[10,22,16,14,20,20,10,14,14,18,14,16,16]);
const itemMap={};for(const o of orders)for(const l of o.lines){const k=l.menu_item_id,item=s.menu.find(i=>i.id===k);if(!itemMap[k])itemMap[k]={Item:l.name_en,Arabic:l.name_ar,Category:item?.category||'',Group:item?.subcategory||'',Quantity:0,Revenue_USD:0,COGS_USD:0};itemMap[k].Quantity+=l.quantity;itemMap[k].Revenue_USD+=l.price_cents*l.quantity/100;itemMap[k].COGS_USD+=orderCost(s,{lines:[l]})}addSheet(wb,'Item Performance',Object.values(itemMap).map(x=>({...x,Gross_Profit_USD:x.Revenue_USD-x.COGS_USD,Margin_Percent:x.Revenue_USD?(x.Revenue_USD-x.COGS_USD)/x.Revenue_USD*100:0})),[24,24,16,18,12,16,14,18,16]);
addSheet(wb,'Expenses',expenses.map(e=>({Date:e.date,Category:e.category,Amount_USD:e.amount,Paid_From:e.paid_from,Note:e.note,Created_By:e.created_by})),[14,20,16,18,35,20]);
addSheet(wb,'Inventory',s.inventory.map(i=>({Item:i.name,Category:i.category,Quantity:i.quantity,Unit:i.unit,Minimum:i.minimum,Unit_Cost_USD:i.unit_cost,Stock_Value_USD:Number(i.quantity||0)*Number(i.unit_cost||0),Low_Stock:Number(i.quantity)<=Number(i.minimum)?'YES':'NO'})),[25,18,14,10,12,18,20,12]);
addSheet(wb,'Shifts',s.shifts.filter(x=>inPeriod(x.opened_at,period)).map(x=>({Cashier:x.user_name,Opened:x.opened_at,Closed:x.closed_at||'',Opening_USD:x.opening_usd,Expected_USD:x.expected_usd??'',Counted_USD:x.closing_usd??'',Variance_USD:x.variance_usd??'',Status:x.status})),[20,22,22,15,15,15,15,12]);
addSheet(wb,'Audit',s.audit.filter(a=>inPeriod(a.at,period)).map(a=>({Date:a.at,Action:a.type,User:a.user||'',Reason:a.reason||'',Item_ID:a.item_id||a.menu_item_id||'',Delta:a.delta??''})),[22,24,20,35,28,12]);
const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});return new NextResponse(bytes,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="cocktaillo-${period}-finance.xlsx"`,'Cache-Control':'no-store'}})}
