import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { getUser, allow } from '../../../../lib/auth.js';
import { readState, orderTotal, orderCost } from '../../../../lib/store.js';
function inPeriod(date,period){const d=new Date(date),n=new Date();if(Number.isNaN(d.getTime()))return false;if(period==='daily')return d.toDateString()===n.toDateString();if(period==='monthly')return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth();return d.getFullYear()===n.getFullYear()}
function addSheet(wb,name,rows,widths=[]){const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{}]);if(widths.length)ws['!cols']=widths.map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,name)}
export async function GET(request){const user=await getUser();if(!allow(user,'manager'))return NextResponse.json({error:'Manager only.'},{status:403});const period=new URL(request.url).searchParams.get('period')||'daily',s=await readState(),rate=Number(s.settings.exchange_rate||89500),orders=s.orders.filter(o=>o.status==='paid'&&inPeriod(o.paid_at||o.created_at,period)),refunded=s.orders.filter(o=>o.status==='refunded'&&inPeriod(o.paid_at||o.created_at,period)),expenses=s.expenses.filter(e=>inPeriod(e.date||e.created_at,period)),purchases=(s.purchases||[]).filter(p=>inPeriod(p.date||p.created_at,period)),sales=orders.reduce((a,o)=>a+orderTotal(o,rate).total_equivalent_cents/100,0),refunds=refunded.reduce((a,o)=>a+orderTotal(o,rate).total_equivalent_cents/100,0),netSales=sales-refunds,cogs=orders.reduce((a,o)=>a+orderCost(s,o),0),exp=expenses.reduce((a,e)=>a+(e.currency==='LBP'?Number(e.amount||0)/rate:Number(e.amount||0)),0),wb=XLSX.utils.book_new();
const paymentUsd=orders.reduce((a,o)=>a+Number(o.payments?.[0]?.usd_cents||0)/100,0),paymentLbp=orders.reduce((a,o)=>a+Number(o.payments?.[0]?.lbp||0),0),refundUsd=refunded.reduce((a,o)=>a+Number((s.refunds||[]).find(r=>r.order_id===o.id)?.payment?.usd_cents||0)/100,0),refundLbp=refunded.reduce((a,o)=>a+Number((s.refunds||[]).find(r=>r.order_id===o.id)?.payment?.lbp||0),0),grossProfit=netSales-cogs,netProfit=grossProfit-exp;
addSheet(wb,'Summary',[{Period:period,Gross_Sales_USD:sales,Refunds_USD:refunds,Net_Sales_USD:netSales,Orders:orders.length,Refunded_Orders:refunded.length,Average_Order_USD:orders.length?sales/orders.length:0,COGS_USD:cogs,Gross_Profit_USD:grossProfit,Expenses_USD_Equivalent:exp,Net_Profit_USD:netProfit,Gross_Margin_Percent:netSales?grossProfit/netSales*100:0,Paid_USD:paymentUsd,Paid_LBP:paymentLbp,Refunded_USD_Cash:refundUsd,Refunded_LBP_Cash:refundLbp,Exchange_Rate:rate,Inventory_Value_USD:s.inventory.reduce((a,i)=>a+Number(i.quantity||0)*Number(i.unit_cost||0),0),Purchases_USD:purchases.reduce((a,p)=>a+Number(p.total_cost||0),0)}]);
addSheet(wb,'Orders',orders.map(o=>{const t=orderTotal(o,rate),p=o.payments?.[0]||{};return {Order:o.number,Date:o.paid_at||o.created_at,Type:o.type,Table:s.tables.find(t=>t.id===o.table_id)?.name||'',Staff:o.created_by_name,Cashier:p.cashier||'',Items:o.lines.reduce((a,l)=>a+l.quantity,0),Subtotal_USD:(t.subtotal_equivalent_cents||t.total_equivalent_cents)/100,Discount_USD:(t.discount_cents||0)/100,Sales_USD:t.total_equivalent_cents/100,COGS_USD:orderCost(s,o),Gross_Profit_USD:t.total_equivalent_cents/100-orderCost(s,o),Paid_USD:(p.usd_cents||0)/100,Paid_LBP:p.lbp||0,Exchange_Rate:p.rate||rate}}));
addSheet(wb,'Refunds',refunded.map(o=>{const t=orderTotal(o,rate),r=(s.refunds||[]).find(x=>x.order_id===o.id)||{};return {Order:o.number,Refunded_At:r.at||'',Reason:r.reason||'',Approved_By:r.user||'',Amount_USD:t.total_equivalent_cents/100,Original_Paid_USD:Number(r.payment?.usd_cents||0)/100,Original_Paid_LBP:Number(r.payment?.lbp||0)}}));
const itemMap={};for(const o of orders)for(const l of o.lines){const k=l.menu_item_id,item=s.menu.find(i=>i.id===k);if(!itemMap[k])itemMap[k]={Item:l.name_en,Arabic:l.name_ar,Category:item?.category||'',Group:item?.subcategory||'',Quantity:0,Revenue_USD:0,COGS_USD:0};itemMap[k].Quantity+=l.quantity;itemMap[k].Revenue_USD+=l.price_cents*l.quantity/100;itemMap[k].COGS_USD+=orderCost(s,{lines:[l]})}addSheet(wb,'Item Performance',Object.values(itemMap).map(x=>({...x,Gross_Profit_USD:x.Revenue_USD-x.COGS_USD,Margin_Percent:x.Revenue_USD?(x.Revenue_USD-x.COGS_USD)/x.Revenue_USD*100:0})));
addSheet(wb,'Expenses',expenses.map(e=>({Date:e.date,Category:e.category,Amount:e.amount,Currency:e.currency,USD_Equivalent:e.currency==='LBP'?Number(e.amount||0)/rate:Number(e.amount||0),Paid_From:e.paid_from,Note:e.note,Created_By:e.created_by})));
addSheet(wb,'Purchases',purchases.map(p=>({Date:p.date,Item:p.item_name,Supplier:p.supplier,Quantity:p.quantity,Unit:p.unit,Unit_Cost_USD:p.unit_cost,Total_Cost_USD:p.total_cost,Invoice:p.invoice,Note:p.note,Created_By:p.created_by})));
addSheet(wb,'Inventory',s.inventory.map(i=>({Item:i.name,Category:i.category,Quantity:i.quantity,Unit:i.unit,Minimum:i.minimum,Unit_Cost_USD:i.unit_cost,Stock_Value_USD:Number(i.quantity||0)*Number(i.unit_cost||0),Low_Stock:Number(i.quantity)<=Number(i.minimum)?'YES':'NO'})));
addSheet(wb,'Shifts',s.shifts.filter(x=>inPeriod(x.opened_at,period)).map(x=>({Cashier:x.user_name,Opened:x.opened_at,Closed:x.closed_at||'',Opening_USD:x.opening_usd,Opening_LBP:x.opening_lbp,Expected_USD:x.expected_usd??'',Expected_LBP:x.expected_lbp??'',Counted_USD:x.closing_usd??'',Counted_LBP:x.closing_lbp??'',Variance_USD:x.variance_usd??'',Variance_LBP:x.variance_lbp??'',Status:x.status})));
addSheet(wb,'Audit',s.audit.filter(a=>inPeriod(a.at,period)).map(a=>({Date:a.at,Action:a.type,User:a.user||'',Reason:a.reason||'',Order_ID:a.order_id||'',Item_ID:a.item_id||a.menu_item_id||'',Delta:a.delta??'',Value:a.value??''})));
const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});return new NextResponse(bytes,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="cocktaillo-${period}-finance.xlsx"`,'Cache-Control':'no-store'}})}
