'use client';
import {useMemo,useState} from 'react';
import {Input,PageHeader,Stat,post,usd} from './ui.js';

export default function OperationsCenter({data,reload}){
 const[pin,setPin]=useState(''),[discount,setDiscount]=useState({order_id:'',type:'percent',value:''}),[purchase,setPurchase]=useState({inventory_id:'',quantity:'',unit_cost:'',supplier:'',invoice:'',note:''});
 const open=data.orders.filter(o=>['open','pending_payment'].includes(o.status));
 const paid=data.orders.filter(o=>o.status==='paid');
 const today=new Date().toDateString();
 const todayOrders=data.orders.filter(o=>new Date(o.paid_at||o.created_at).toDateString()===today);
 const todayPaid=todayOrders.filter(o=>o.status==='paid');
 const todayRefunds=todayOrders.filter(o=>o.status==='refunded');
 const sales=todayPaid.reduce((s,o)=>s+(o.totals?.total_equivalent_cents||0),0),refunds=todayRefunds.reduce((s,o)=>s+(o.totals?.total_equivalent_cents||0),0);
 async function action(payload){try{await post('/api/actions',{...payload,manager_pin:pin});setPin('');await reload()}catch(e){alert(e.message)}}
 async function doDiscount(){await action({action:'apply_discount',order_id:discount.order_id,discount_type:discount.type,value:discount.value});setDiscount({...discount,value:''})}
 async function voidOrder(o){const reason=prompt(`Void Order #${o.number}. Reason:`);if(!reason)return;await action({action:'void_order',order_id:o.id,reason})}
 async function refundOrder(o){const reason=prompt(`Refund Order #${o.number}. Reason:`);if(!reason)return;if(!confirm(`Refund full order #${o.number}? Inventory recipe quantities will be restored.`))return;await action({action:'refund_order',order_id:o.id,reason})}
 async function merge(){const source=prompt('Source table ID/name number (example table-1):');const target=prompt('Target table ID/name number (example table-2):');if(!source||!target)return;await action({action:'merge_tables',source_table_id:source,target_table_id:target})}
 async function buy(){try{await post('/api/admin',{action:'purchase_stock',...purchase});setPurchase({inventory_id:'',quantity:'',unit_cost:'',supplier:'',invoice:'',note:''});await reload()}catch(e){alert(e.message)}}
 function exportClosing(){const rows=[['COCKTAILLO END OF DAY',new Date().toLocaleString()],['Gross sales',sales/100],['Refunds',refunds/100],['Net sales',(sales-refunds)/100],['Orders',todayPaid.length],['Refunded orders',todayRefunds.length],[],['Order #','Type','Status','Total','Cashier','Time'],...todayOrders.map(o=>[o.number,o.type,o.status,((o.totals?.total_equivalent_cents||0)/100).toFixed(2),o.payments?.[0]?.cashier||'',o.paid_at||o.created_at])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cocktaillo-end-of-day-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const low=useMemo(()=>(data.inventory||[]).filter(i=>Number(i.quantity)<=Number(i.minimum)),[data.inventory]);
 return <><PageHeader title="Operations Control" sub="Manager controls for discounts, voids, refunds, stock purchasing, table merge and end-of-day audit."/>
 <div className="cards"><Stat label="Today's net sales" value={usd(sales-refunds)}/><Stat label="Today's orders" value={todayPaid.length}/><Stat label="Refunds" value={usd(refunds)}/><Stat label="Low stock" value={low.length}/></div>
 <div className="card section"><h3>Manager approval PIN</h3><Input label="PIN (needed when cashier performs protected actions)" type="password" value={pin} onChange={setPin}/></div>
 <div className="card section"><h3>Discount open order</h3><div className="formGrid"><div className="field"><label>Order</label><select className="input" value={discount.order_id} onChange={e=>setDiscount({...discount,order_id:e.target.value})}><option value="">Choose order…</option>{open.map(o=><option key={o.id} value={o.id}>#{o.number} · {o.type} · {usd(o.totals?.total_equivalent_cents||0)}</option>)}</select></div><div className="field"><label>Discount type</label><select className="input" value={discount.type} onChange={e=>setDiscount({...discount,type:e.target.value})}><option value="percent">Percent %</option><option value="fixed">Fixed USD</option></select></div><Input label="Value" value={discount.value} onChange={v=>setDiscount({...discount,value:v})}/><button className="btn btnPrimary" onClick={doDiscount}>Apply Discount</button></div></div>
 <div className="card section"><h3>Open checks</h3><div className="list">{open.map(o=><div className="listRow" key={o.id}><div className="grow"><strong>#{o.number} · {o.type}</strong><small style={{display:'block'}}>{usd(o.totals?.total_equivalent_cents||0)} · {o.created_by_name}</small></div><button className="btn btnDanger" onClick={()=>voidOrder(o)}>Void</button></div>)}</div><button className="btn btnSoft" style={{marginTop:10}} onClick={merge}>Merge Two Open Tables</button></div>
 <div className="card section"><h3>Paid orders / refunds</h3><div className="list">{paid.slice(0,30).map(o=><div className="listRow" key={o.id}><div className="grow"><strong>#{o.number} · {usd(o.totals?.total_equivalent_cents||0)}</strong><small style={{display:'block'}}>{o.payments?.[0]?.cashier||''} · {new Date(o.paid_at).toLocaleString()}</small></div><button className="btn btnDanger" onClick={()=>refundOrder(o)}>Refund</button></div>)}</div></div>
 <div className="card section"><h3>Stock In / Purchase</h3><div className="formGrid"><div className="field"><label>Inventory item</label><select className="input" value={purchase.inventory_id} onChange={e=>setPurchase({...purchase,inventory_id:e.target.value})}><option value="">Choose item…</option>{(data.inventory||[]).map(i=><option key={i.id} value={i.id}>{i.name} · {i.quantity} {i.unit}</option>)}</select></div><Input label="Quantity received" value={purchase.quantity} onChange={v=>setPurchase({...purchase,quantity:v})}/><Input label="Unit cost USD" value={purchase.unit_cost} onChange={v=>setPurchase({...purchase,unit_cost:v})}/><Input label="Supplier" value={purchase.supplier} onChange={v=>setPurchase({...purchase,supplier:v})}/><Input label="Invoice #" value={purchase.invoice} onChange={v=>setPurchase({...purchase,invoice:v})}/><Input label="Note" value={purchase.note} onChange={v=>setPurchase({...purchase,note:v})}/><button className="btn btnPrimary" onClick={buy}>Receive Stock</button></div></div>
 {low.length>0&&<div className="card section"><h3>Low-stock alerts</h3><div className="list">{low.map(i=><div className="listRow" key={i.id}><div className="grow"><strong>{i.name}</strong><small style={{display:'block'}}>{i.quantity} {i.unit} remaining · minimum {i.minimum}</small></div></div>)}</div></div>}
 <div className="card section"><h3>End of Day</h3><p style={{color:'var(--muted)'}}>Export today's gross sales, refunds, net sales, order count and transaction details for closing/audit.</p><button className="btn btnPrimary" onClick={exportClosing}>Export End-of-Day Closing</button></div></>
}
