'use client';
const TOKEN_KEY='cocktaillo_print_agent_token';let installed=false;let nativeFetch=null;
function emit(detail){if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('cocktaillo-print-status',{detail}))}
export function getPrintAgentToken(){return typeof window==='undefined'?'':localStorage.getItem(TOKEN_KEY)||''}
export function setPrintAgentToken(token){if(typeof window!=='undefined'){if(token)localStorage.setItem(TOKEN_KEY,String(token).trim());else localStorage.removeItem(TOKEN_KEY)}}
async function serverPost(body){const f=nativeFetch||fetch;const r=await f('/api/print-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Print server HTTP ${r.status}`);return d}
function candidateAgentUrls(url){const primary=String(url||'http://127.0.0.1:17483').replace(/\/$/,'');const out=[primary];try{const u=new URL(primary);if(u.hostname==='127.0.0.1')out.push(`${u.protocol}//localhost${u.port?`:${u.port}`:''}`);else if(u.hostname==='localhost')out.push(`${u.protocol}//127.0.0.1${u.port?`:${u.port}`:''}`)}catch{}return [...new Set(out)]}
async function agentRequest(url,path,token,options={}){const f=nativeFetch||fetch;let lastError=null;for(const base of candidateAgentUrls(url)){try{const r=await f(`${base}${path}`,{...options,mode:'cors',credentials:'omit',cache:'no-store',headers:{...(options.headers||{}),'Authorization':`Bearer ${token}`,'Content-Type':'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Local print agent HTTP ${r.status}`);return {...d,_agent_url:base}}catch(e){lastError=e}}const error=new Error(`Could not connect to the local print agent. Tried ${candidateAgentUrls(url).join(' and ')}. If the agent is running, allow Local network access for this site in Chrome. ${lastError?.message||''}`.trim());error.cause=lastError;throw error}
async function executeJob(bundle){const {job,receipt,agent_url,printer_name,should_print}=bundle;if(!should_print){if(job?.status==='printed')emit({status:'printed',jobId:job.id,receiptId:job.receipt_id,message:`Receipt #${job.order_number} already printed.`});return bundle}const token=getPrintAgentToken();if(!token){const e=Object.assign(new Error('Local print agent is not paired. Open Settings → Customer Receipt Printer and enter the agent token.'),{jobId:job.id,receiptId:job.receipt_id});await serverPost({action:'status',job_id:job.id,status:'failed',error:e.message}).catch(()=>{});throw e}await serverPost({action:'status',job_id:job.id,status:'printing'});try{await agentRequest(agent_url,'/print',token,{method:'POST',body:JSON.stringify({job_id:job.id,destination:'customer',printer_name,receipt})});await serverPost({action:'status',job_id:job.id,status:'printed'});emit({status:'printed',jobId:job.id,receiptId:job.receipt_id,message:`Customer receipt #${job.order_number} printed.`});return bundle}catch(e){await serverPost({action:'status',job_id:job.id,status:'failed',error:e.message}).catch(()=>{});throw Object.assign(e,{jobId:job.id,receiptId:job.receipt_id})}}
export async function autoPrintCustomerReceipt(receiptId){try{const bundle=await serverPost({action:'create',receipt_id:receiptId,mode:'automatic'});return await executeJob(bundle)}catch(e){emit({status:'failed',jobId:e.jobId||null,receiptId:e.receiptId||receiptId,message:'Receipt printing failed',error:e.message});throw e}}
export async function reprintCustomerReceipt(receiptId){try{const bundle=await serverPost({action:'create',receipt_id:receiptId,mode:'reprint'});return await executeJob(bundle)}catch(e){emit({status:'failed',jobId:e.jobId||null,receiptId:e.receiptId||receiptId,message:'Receipt printing failed',error:e.message});throw e}}
export async function retryPrintJob(jobId){try{const bundle=await serverPost({action:'retry',job_id:jobId});return await executeJob(bundle)}catch(e){emit({status:'failed',jobId:e.jobId||jobId,receiptId:e.receiptId||null,message:'Receipt printing failed',error:e.message});throw e}}
export async function testPrintAgent(agentUrl,token){return agentRequest(agentUrl,'/health',token,{method:'GET'})}
export async function listAgentPrinters(agentUrl,token){const r=await agentRequest(agentUrl,'/printers',token,{method:'GET'});return Array.isArray(r.printers)?r.printers:[]}
export function installPrintBridgeInterceptor(){if(installed||typeof window==='undefined')return()=>{};installed=true;nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){const response=await nativeFetch(input,init);try{const url=typeof input==='string'?input:input?.url||'';if(response.ok&&init?.method?.toUpperCase()==='POST'&&(url.includes('/api/actions')||url.includes('/api/split-pay'))){const cloned=response.clone();cloned.json().then(d=>{if(d?.receipt?.id)void autoPrintCustomerReceipt(d.receipt.id)}).catch(()=>{})}}catch{}return response};return()=>{if(nativeFetch){window.fetch=nativeFetch;installed=false}}}
