'use client';
import {useEffect,useRef,useState} from 'react';
import {Input,PageHeader,post} from './ui.js';
import {getLocalPrintSettings,saveLocalPrintSettings,testLocalPrintService} from './print-client.js';

export default function SettingsPanel({data,reload}){
  const[rate,setRate]=useState(String(data.settings.exchange_rate)),[footer,setFooter]=useState(data.settings.receipt_footer||''),[theme,setTheme]=useState(data.settings.theme||'light'),[pin,setPin]=useState(''),[resetText,setResetText]=useState(''),[busy,setBusy]=useState(false),[printerStatus,setPrinterStatus]=useState('Not connected on this device'),[printers,setPrinters]=useState([]),[localPrint,setLocalPrint]=useState(()=>({serviceUrl:'http://127.0.0.1:17483',token:'',customerPrinter:'Customer Receipt',barPrinter:'Bar Printer',paperWidth:80}));
  const fileRef=useRef(null);
  useEffect(()=>setLocalPrint(getLocalPrintSettings()),[]);
  function previewTheme(value){setTheme(value);document.documentElement.dataset.theme=value}
  async function save(){setBusy(true);try{await post('/api/actions',{action:'save_settings',settings:{exchange_rate:rate,receipt_footer:footer,theme}});await reload();alert('Settings saved.')}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function connectPrinters(){setBusy(true);setPrinterStatus('Connecting…');try{const next=saveLocalPrintSettings(localPrint),result=await testLocalPrintService(next);setPrinters(result.printers);let updated=next;if(!result.printers.includes(next.customerPrinter)&&result.printers.length)updated={...updated,customerPrinter:result.printers[0]};if(!result.printers.includes(next.barPrinter)&&result.printers.length===1)updated={...updated,barPrinter:result.printers[0]};updated=saveLocalPrintSettings(updated);setLocalPrint(updated);setPrinterStatus(`Connected · ${result.printers.length} Windows printer${result.printers.length===1?'':'s'} found`)}catch(e){setPrinterStatus(`Could not connect: ${e.message}`)}finally{setBusy(false)}}
  function savePrinterSetup(){const next=saveLocalPrintSettings(localPrint);setLocalPrint(next);setPrinterStatus('Printer setup saved on this Windows device.');}
  async function savePin(){if(!/^\d{4,8}$/.test(pin))return alert('PIN must be 4 to 8 digits.');setBusy(true);try{await post('/api/actions',{action:'save_manager_pin',pin});setPin('');alert('Manager approval PIN saved securely.')}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function restore(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!confirm('Restore this FULL backup? Current system data will be replaced.'))return;setBusy(true);try{const backup=JSON.parse(await file.text());const r=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(backup)}),out=await r.json();if(!r.ok)throw new Error(out.error||'Restore failed.');alert(out.message||'Backup restored.');await reload()}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function factoryReset(){if(resetText!=='RESET COCKTAILLO')return alert('Type RESET COCKTAILLO exactly.');if(!confirm('Permanently reset transactional data?'))return;setBusy(true);try{await post('/api/actions',{action:'factory_reset',confirmation:resetText});setResetText('');await reload();alert('Factory reset completed.')}catch(e){alert(e.message)}finally{setBusy(false)}}
  const printerOptions=printers.length?printers:Array.from(new Set([localPrint.customerPrinter,localPrint.barPrinter].filter(Boolean)));
  return <><PageHeader title="Settings" sub="Business configuration, security, printers, backups and protected reset."/>
    <div className="card" style={{maxWidth:820}}><h3>General</h3><div className="formGrid"><Input label="USD / LBP exchange rate" value={rate} onChange={setRate}/><Input label="Receipt footer" value={footer} onChange={setFooter}/></div><div className="field section"><label>Appearance</label><div className="themeChooser"><button type="button" className={`themeChoice ${theme==='light'?'active':''}`} onClick={()=>previewTheme('light')}>Light mode</button><button type="button" className={`themeChoice ${theme==='dark'?'active':''}`} onClick={()=>previewTheme('dark')}>Dark mode</button></div></div><button disabled={busy} className="btn btnPrimary" style={{marginTop:10}} onClick={save}>Save General Settings</button></div>
    <div className="card section" style={{maxWidth:820}}><h3>POS Printing</h3><p style={{color:'var(--muted)'}}>No QZ Tray is required. Install the Cocktaillo Print Agent once on the cashier Windows PC, paste its pairing token here, connect, choose the receipt and bar printers, then save. Waiter phones need no printer setup.</p><div className="formGrid"><Input label="Local Print Agent URL" value={localPrint.serviceUrl} onChange={value=>setLocalPrint(s=>({...s,serviceUrl:value}))}/><Input label="Pairing token" type="password" value={localPrint.token} onChange={value=>setLocalPrint(s=>({...s,token:value}))}/><div className="field"><label>Customer receipt printer</label><select className="input" value={localPrint.customerPrinter} onChange={e=>setLocalPrint(s=>({...s,customerPrinter:e.target.value}))}>{printerOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div className="field"><label>Bar printer</label><select className="input" value={localPrint.barPrinter} onChange={e=>setLocalPrint(s=>({...s,barPrinter:e.target.value}))}>{printerOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div className="field"><label>Paper width</label><select className="input" value={localPrint.paperWidth} onChange={e=>setLocalPrint(s=>({...s,paperWidth:Number(e.target.value)}))}><option value={80}>80 mm</option><option value={58}>58 mm</option></select></div><div className="field"><label>Status on this device</label><div className="input" style={{minHeight:50,display:'flex',alignItems:'center'}}>{printerStatus}</div></div></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="btn btnSoft" disabled={busy||!localPrint.token.trim()} onClick={connectPrinters}>{busy?'Connecting…':'Connect & Load Printers'}</button><button className="btn btnPrimary" disabled={!localPrint.token.trim()} onClick={savePrinterSetup}>Save Printer Setup</button></div><small style={{display:'block',marginTop:10,color:'var(--muted)'}}>Bar tickets sent by waiter phones are queued on the server and printed automatically by this Windows device. If the printer is temporarily offline, the ticket stays queued and retries instead of being lost.</small></div>
    <div className="card section" style={{maxWidth:820}}><h3>Manager Approval PIN</h3><p style={{color:'var(--muted)'}}>Used to approve protected POS actions such as discounts, voids and refunds when required.</p><Input label="New PIN (4–8 digits)" type="password" value={pin} onChange={setPin}/><button className="btn btnPrimary" style={{marginTop:10}} disabled={busy||!pin} onClick={savePin}>Set / Change Manager PIN</button></div>
    <div className="card section" style={{maxWidth:820}}><h3>Backup & Restore</h3><p style={{color:'var(--muted)'}}>Full backup includes users, menu, tables, inventory, recipes, orders, receipts, shifts, expenses, purchases, refunds, audit and settings.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btnPrimary" onClick={()=>{window.location.href='/api/backup'}}>Download Full Backup</button><button className="btn btnSoft" disabled={busy} onClick={()=>fileRef.current?.click()}>Upload & Restore</button><input ref={fileRef} hidden type="file" accept=".json,application/json" onChange={restore}/></div></div>
    <div className="card dangerZone section" style={{maxWidth:820}}><h3>Factory Reset</h3><p>Resets orders, receipts, shifts, tickets, expenses, purchases, refunds, reservations and stock quantities while preserving catalog/configuration and the current Manager account.</p><Input label="Type RESET COCKTAILLO" value={resetText} onChange={setResetText}/><button disabled={busy||resetText!=='RESET COCKTAILLO'} className="btn btnDanger" style={{marginTop:12}} onClick={factoryReset}>Factory Reset System</button></div>
  </>}
