import {queuePaidReceipt} from '../../../lib/receipt-job.js';
import {cashAmount} from '../../../lib/shift-report.js';
import {cashShift,changeFor} from '../../../lib/cash.js';
import {NextResponse} from 'next/server';
import bcrypt from 'bcryptjs';
import {getUser,allow} from '../../../lib/auth.js';
import {deductRecipes,restoreRecipes,mutateState,orderTotal,publicUser} from '../../../lib/store.js';
import {refundAmountForItems,restoreRefundedRecipes,makeRefundPayment,refundableLines} from '../../../lib/refunds.js';
async function managerApproved(state,user,pin){if(user.role==='manager')return true;const hash=state.settings?.manager_pin_hash;if(!hash||!pin)return false;return bcrypt.compare(String(pin),hash)}
const nonNegativeNumber=(v,l)=>{const n=Number(v??0);if(!Number.isFinite(n)||n<0)throw new Error(`${l} must be a valid non-negative number.`);return n};
const positiveNumber=(v,l)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error(`${l} must be a valid positive number.`);return n};
const activeShift=cashShift;
const mainWaiter=user=>user.role==='waiter'&&String(user.username||'').trim().toLowerCase()==='bako';
export async function POST(request){const user=await getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json().catch(()=>({}));try{const data=await mutateState(async s=>{const now=new Date().toISOString();
 if(b.action==='open_shift'){if(!allow(user,'cashier','manager'))throw new Error('Not allowed.');if(s.shifts.some(x=>x.user_id===user.id&&x.status==='open'))throw new Error('Shift already open.');const shift={id:`shift-${crypto.randomUUID()}`,user_id:user.id,user_name:user.name,status:'open',opened_at:now,opening_usd:cashAmount(b.opening_usd??0,'USD')/100,opening_lbp:cashAmount(b.opening_lbp??0,'LBP'),closed_at:null,closing_usd:null,closing_lbp:null,expected_usd:null,expected_lbp:null,variance_usd:null,variance_lbp:null};s.shifts.push(shift);return {shift}}
 if(b.action==='apply_discount'){if(!allow(user,'cashier','manager'))throw new Error('Cashier access required.');if(b.discount_type==='fixed'&&user.role!=='manager'&&!(await managerApproved(s,user,b.manager_pin)))throw new Error('Manager approval required for a fixed discount.');const order=s.orders.find(x=>x.id===b.order_id&&['open','pending_payment'].includes(x.status));if(!order)throw new Error('Open order not found.');const type=b.discount_type==='fixed'?'fixed':'percent',value=nonNegativeNumber(b.value,'Discount value');if(type==='percent'&&value>100)throw new Error('Percent cannot exceed 100.');order.discount={type,value,approved_by:type==='percent'?user.name:(user.role==='manager'?user.name:'Manager PIN'),at:now};s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'discount_applied',order_id:order.id,value,discount_type:type,user:user.name,at:now});return {order,total:orderTotal(order,s.settings.exchange_rate)}}
 if(b.action==='pay_order'){if(!allow(user,'cashier','manager'))throw new Error('Cashier access required.');if(user.role==='cashier'&&!s.shifts.some(x=>x.user_id===user.id&&x.status==='open'))throw new Error('Open your shift before collecting payment.');const existing=s.receipts.find(r=>r.order_id===b.order_id);if(existing){queuePaidReceipt(s,existing,now);return {receipt:existing}};const order=s.orders.find(x=>x.id===b.order_id&&['open','pending_payment'].includes(x.status));if(!order)throw new Error('Order not found.');const rate=positiveNumber(s.settings.exchange_rate,'Exchange rate'),usd=cashAmount(b.usd||0,'USD')/100,lbp=cashAmount(b.lbp||0,'LBP'),totals=orderTotal(order,rate),usdCents=Math.round(usd*100),lbpAmount=Math.round(lbp),paid=usdCents+Math.round(lbpAmount/rate*100);if(paid<totals.total_equivalent_cents)throw new Error('Payment is less than total.');order.payments=[{usd_cents:usdCents,lbp:lbpAmount,rate,cashier:user.name,at:now}];order.status='paid';order.paid_at=now;deductRecipes(s,order);const shift=activeShift(s,user),receipt={id:`rcpt-${crypto.randomUUID()}`,number:order.number,order_id:order.id,type:order.type,table_id:order.table_id,items:order.lines,totals,payment:order.payments[0],discount:order.discount||null,change_cents:paid-totals.total_equivalent_cents,change_payment:changeFor(paid-totals.total_equivalent_cents,b.change_currency,rate),shift_id:shift?.id,cashier_id:user.id,cashier:user.name,created_at:now};s.receipts.push(receipt);queuePaidReceipt(s,receipt,now);return {receipt}}
 if(b.action==='void_order'){if(!allow(user,'cashier','manager'))throw new Error('Cashier access required.');if(!(await managerApproved(s,user,b.manager_pin)))throw new Error('Manager approval required.');const order=s.orders.find(x=>x.id===b.order_id&&['open','pending_payment'].includes(x.status));if(!order)throw new Error('Only unpaid/open orders can be voided.');const reason=String(b.reason||'').trim();if(!reason)throw new Error('Void reason is required.');order.status='void';order.void={reason,user:user.name,at:now};s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'order_voided',order_id:order.id,reason,user:user.name,at:now});return {order}}
 if(b.action==='refund_order'||b.action==='refund_items'){if(!allow(user,'cashier','manager'))throw new Error('Cashier access required.');if(user.role==='cashier'&&!s.shifts.some(x=>x.user_id===user.id&&x.status==='open'))throw new Error('Open your shift before issuing a refund.');const order=s.orders.find(x=>x.id===b.order_id&&['paid','partially_refunded'].includes(x.status));if(!order)throw new Error('Paid order not found.');const reason=String(b.reason||'').trim();if(!reason)throw new Error('Refund reason is required.');const receipt=s.receipts.find(r=>r.order_id===order.id),rate=Number(receipt?.payment?.rate||s.settings.exchange_rate),currency=b.refund_currency==='LBP'?'LBP':'USD';let items,amount;if(b.action==='refund_order'){items=refundableLines(s,order).filter(l=>l.refundable_quantity>0).map(l=>({line_id:l.id,menu_item_id:l.menu_item_id,name_en:l.name_en,name_ar:l.name_ar,quantity:l.refundable_quantity}));const remaining=Math.max(0,Number(receipt?.totals?.total_equivalent_cents||orderTotal(order,rate).total_equivalent_cents)-(s.refunds||[]).filter(r=>r.order_id===order.id).reduce((sum,r)=>sum+Number(r.amount_cents||0),0));amount=remaining}else{const calc=refundAmountForItems(s,order,Array.isArray(b.items)?b.items:[],rate);items=calc.items;amount=calc.amount_cents}if(!items.length||amount<=0)throw new Error('Nothing refundable remains on this order.');const payment=makeRefundPayment(amount,currency,rate),shift=activeShift(s,user),refund={id:`refund-${crypto.randomUUID()}`,kind:b.action==='refund_order'?'full':'items',order_id:order.id,order_number:order.number,shift_id:shift?.id,cashier_id:user.id,amount_cents:amount,payment:{usd_cents:Number(payment.usd_cents||0),lbp:Number(payment.lbp||0)},items,reason,user:user.name,at:now};s.refunds.push(refund);restoreRefundedRecipes(s,items);const totalRefunded=s.refunds.filter(r=>r.order_id===order.id).reduce((sum,r)=>sum+Number(r.amount_cents||0),0),orderTotalCents=Number(receipt?.totals?.total_equivalent_cents||orderTotal(order,rate).total_equivalent_cents);order.status=totalRefunded>=orderTotalCents?'refunded':'partially_refunded';order.refund_id=order.status==='refunded'?refund.id:null;if(receipt){receipt.refund_usd=totalRefunded/100;receipt.refunded_at=now} s.audit.push({id:`audit-${crypto.randomUUID()}`,type:b.action==='refund_order'?'order_refunded':'items_refunded',order_id:order.id,refund_id:refund.id,amount_cents:amount,items:items.map(i=>({line_id:i.line_id,quantity:i.quantity})),reason,user:user.name,at:now});return {refund,order}}
 if(b.action==='transfer_table'||b.action==='transfer_items'){if(user.role==='waiter'&&!mainWaiter(user))throw new Error('Only the main waiter bako can transfer table items.');if(!allow(user,'waiter','cashier','manager'))throw new Error('Not allowed.');const source=s.orders.find(x=>x.id===b.order_id&&x.type==='table'&&x.status==='open');if(!source)throw new Error('Open table order not found.');if(user.role==='waiter'&&source.created_by!==user.id&&!mainWaiter(user))throw new Error('This table belongs to another waiter.');if(!s.tables.some(x=>x.id===b.to_table_id))throw new Error('Destination table not found.');if(b.action==='transfer_table'){if(s.orders.some(x=>x.type==='table'&&x.table_id===b.to_table_id&&x.status==='open'))throw new Error('Destination table is occupied.');source.table_id=b.to_table_id;source.updated_at=now;s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'table_transferred',order_id:source.id,to_table_id:b.to_table_id,user:user.name,at:now});return {order:source}}const line=source.lines.find(l=>l.id===b.line_id),qty=Math.floor(Number(b.quantity||0));if(!line||qty<1||qty>Number(line.quantity||0))throw new Error('Invalid item quantity.');let target=s.orders.find(x=>x.type==='table'&&x.table_id===b.to_table_id&&x.status==='open');if(!target){target={id:`ord-${crypto.randomUUID()}`,number:s.next_order_number++,type:'table',table_id:b.to_table_id,customer:null,created_by:user.id,created_by_name:user.name,status:'open',created_at:now,updated_at:now,lines:[],payments:[]};s.orders.push(target)}const moved={...line,id:`line-${crypto.randomUUID()}`,quantity:qty};target.lines.push(moved);if(qty===Number(line.quantity))source.lines=source.lines.filter(l=>l.id!==line.id);else line.quantity-=qty;source.updated_at=target.updated_at=now;if(!source.lines.length){source.status='transferred';source.transferred_into=target.id}s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'items_transferred',source_order:source.id,target_order:target.id,line_id:line.id,quantity:qty,to_table_id:b.to_table_id,user:user.name,at:now});return {source,target}}
 if(b.action==='merge_tables'){if(!allow(user,'cashier','manager'))throw new Error('Cashier access required.');const source=s.orders.find(x=>x.type==='table'&&x.table_id===b.source_table_id&&x.status==='open'),target=s.orders.find(x=>x.type==='table'&&x.table_id===b.target_table_id&&x.status==='open');if(!source||!target||source.id===target.id)throw new Error('Both tables must have separate open checks.');if(source.discount||target.discount)throw new Error('Remove table discounts before merging checks to keep accounting exact.');target.lines.push(...source.lines);target.updated_at=now;source.status='merged';source.merged_into=target.id;s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'tables_merged',source_order:source.id,target_order:target.id,user:user.name,at:now});return {order:target}}
 if(b.action==='ticket_status'){if(!allow(user,'cashier','manager'))throw new Error('Not allowed.');const ticket=s.tickets.find(x=>x.id===b.ticket_id);if(!ticket)throw new Error('Ticket not found.');if(!['new','preparing','ready'].includes(b.status))throw new Error('Invalid status.');ticket.status=b.status;ticket.updated_at=now;return {ticket}}
 if(b.action==='add_user'){if(!allow(user,'manager'))throw new Error('Manager only.');if(!['cashier','waiter','manager'].includes(b.role))throw new Error('Invalid role.');const username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');if(s.users.some(x=>x.username===username))throw new Error('Username exists.');if(password.length<8)throw new Error('Password must be at least 8 characters.');const u={id:`u-${crypto.randomUUID()}`,name:String(b.name||'').trim(),username,password_hash:await bcrypt.hash(password,10),role:b.role,active:true};if(!u.name||!u.username)throw new Error('Name and username are required.');s.users.push(u);s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'user_created',target_user:u.username,user:user.name,at:now});return {user:publicUser(u)}}
 if(b.action==='update_user'){if(!allow(user,'manager'))throw new Error('Manager only.');const target=s.users.find(x=>x.id===b.id);if(!target)throw new Error('User not found.');const name=String(b.name||'').trim(),username=String(b.username||'').trim().toLowerCase(),role=String(b.role||target.role);if(!name||!username)throw new Error('Name and username are required.');if(!['cashier','waiter','manager'].includes(role))throw new Error('Invalid role.');if(s.users.some(x=>x.id!==target.id&&x.username===username))throw new Error('Username exists.');if(target.id===user.id&&role!=='manager')throw new Error('You cannot remove your own Manager role.');target.name=name;target.username=username;target.role=role;target.active=b.active!==false;if(String(b.password||'').trim()){if(String(b.password).length<8)throw new Error('New password must be at least 8 characters.');target.password_hash=await bcrypt.hash(String(b.password),10)}s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'user_updated',target_user:target.username,user:user.name,at:now});return {user:publicUser(target)}}
 if(b.action==='delete_user'){if(!allow(user,'manager'))throw new Error('Manager only.');const target=s.users.find(x=>x.id===b.id);if(!target)throw new Error('User not found.');if(target.id===user.id)throw new Error('You cannot delete your own Manager account.');if(target.role==='manager'&&s.users.filter(x=>x.role==='manager'&&x.active).length<=1)throw new Error('At least one active Manager account is required.');s.users=s.users.filter(x=>x.id!==target.id);s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'user_deleted',target_user:target.username,user:user.name,at:now});return {ok:true}}
 if(b.action==='add_expense'){if(!allow(user,'manager'))throw new Error('Manager only.');const amount=positiveNumber(b.amount,'Expense amount'),e={id:`exp-${crypto.randomUUID()}`,date:b.date||now.slice(0,10),category:b.category||'Other',amount,currency:b.currency==='LBP'?'LBP':'USD',paid_from:b.paid_from||'owner',shift_id:b.paid_from==='cash_drawer'?activeShift(s,user)?.id:null,note:b.note||'',created_by:user.name,created_at:now};s.expenses.push(e);return {expense:e}}
 if(b.action==='save_manager_pin'){if(!allow(user,'manager'))throw new Error('Manager only.');const pin=String(b.pin||'');if(!/^\d{4,8}$/.test(pin))throw new Error('PIN must be 4 to 8 digits.');s.settings.manager_pin_hash=await bcrypt.hash(pin,10);s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'manager_pin_changed',user:user.name,at:now});return {ok:true}}
 if(b.action==='save_settings'){if(!allow(user,'manager'))throw new Error('Manager only.');const nextTheme=['light','dark'].includes(b.settings?.theme)?b.settings.theme:s.settings.theme||'light',exchangeRate=positiveNumber(b.settings?.exchange_rate??s.settings.exchange_rate,'Exchange rate'),safe={...b.settings};delete safe.manager_pin_hash;s.settings={...s.settings,...safe,theme:nextTheme,exchange_rate:exchangeRate};return {settings:s.settings}}
 if(b.action==='factory_reset'){if(!allow(user,'manager'))throw new Error('Manager only.');if(String(b.confirmation||'')!=='RESET COCKTAILLO')throw new Error('Type RESET COCKTAILLO to confirm.');const manager=s.users.find(x=>x.id===user.id)||s.users.find(x=>x.role==='manager');s.users=manager?[manager]:[];s.shifts=[];s.orders=[];s.receipts=[];s.tickets=[];s.expenses=[];s.purchases=[];s.refunds=[];s.reservations=[];s.audit=[];s.next_order_number=1;s.order_requests=[];s.shift_reports=[];s.report_deliveries=[];s.print_jobs=[];s.inventory=(s.inventory||[]).map(i=>({...i,quantity:0,updated_at:now}));s.tables=(s.tables||[]).map(t=>({...t,status:'available'}));s.audit.push({id:`audit-${crypto.randomUUID()}`,type:'factory_reset',user:user.name,at:now});return {ok:true}}
 throw new Error('Unknown action.');});return NextResponse.json(data)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Action failed.'},{status:400})}}

