import * as XLSX from 'xlsx';
import {financeLedger,inFinancePeriod} from './finance-ledger.js';
import {orderCost,orderTotal} from './store.js';
function sheet(wb,name,rows,widths){const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{}]);ws['!cols']=(widths||[]).map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,name)}
export function buildDailyWorkbook(state,anchor=new Date()){const ledger=financeLedger(state,{period:'daily',anchor}),rate=ledger.exchange_rate,orders=(state.orders||[]).filter(o=>['paid','partially_refunded','refunded'].includes(o.status)&&inFinancePeriod(o.paid_at||o.updated_at||o.created_at,'daily',anchor)),refunds=(state.refunds||[]).filter(r=>inFinancePeriod(r.at,'daily',anchor)),wb=XLSX.utils.book_new(),date=new Date(anchor).toISOString().slice(0,10);
 sheet(wb,'Executive Summary',[{Business:'COCKTAILLO',Report_Date:date,Generated_At:new Date().toISOString(),Gross_Sales_USD:ledger.gross_sales_cents/100,Refunds_USD:ledger.refunds_cents/100,Net_Sales_USD:ledger.net_sales_cents/100,Discounts_USD:ledger.discounts_cents/100,Orders:ledger.orders,Orders_With_Refunds:ledger.refunded_orders,COGS_USD:ledger.cogs_usd,Gross_Profit_USD:ledger.gross_profit_usd,Expenses_USD:ledger.expenses_usd,Net_Profit_USD:ledger.net_profit_usd,Paid_USD:ledger.paid_usd,Paid_LBP:ledger.paid_lbp,Refunded_USD:ledger.refunded_usd,Refunded_LBP:ledger.refunded_lbp,Net_Cash_USD:ledger.net_cash_usd,Net_Cash_LBP:ledger.net_cash_lbp,Exchange_Rate:rate,Inventory_Value_USD:ledger.inventory_value_usd}], [20,18,24,18,18,18,18]);
 sheet(wb,'Orders',orders.map(o=>{const receipt=(state.receipts||[]).find(r=>r.order_id===o.id),t=receipt?.totals||orderTotal(o,rate),ref=refunds.filter(r=>r.order_id===o.id).reduce((s,r)=>s+Number(r.amount_cents||0),0);return {Order:o.number,Paid_At:o.paid_at,Status:o.status,Type:o.type,Table:state.tables.find(t=>t.id===o.table_id)?.name||'',Waiter:o.created_by_name||'',Cashier:receipt?.cashier||o.payments?.[0]?.cashier||'',Items:(o.lines||[]).reduce((s,l)=>s+Number(l.quantity||0),0),Gross_USD:Number(t.total_equivalent_cents||0)/100,Refunded_USD:ref/100,Net_USD:(Number(t.total_equivalent_cents||0)-ref)/100,Discount_USD:Number(t.discount_cents||0)/100,COGS_USD:orderCost(state,o)}}),[10,23,20,14,14,20,20,10,14,14,14,14,14]);
 const itemRows=[];for(const o of orders)for(const l of o.lines||[]){const refunded=refunds.filter(r=>r.order_id===o.id).flatMap(r=>r.items||[]).filter(i=>i.line_id===l.id).reduce((s,i)=>s+Number(i.quantity||0),0);itemRows.push({Order:o.number,Item:l.name_en,Arabic:l.name_ar,Category:l.category||'',Subcategory:l.subcategory||'',Sold_Qty:l.quantity,Refunded_Qty:refunded,Net_Qty:Number(l.quantity||0)-refunded,Unit_USD:Number(l.price_cents||0)/100,Notes:l.note||''})}sheet(wb,'Item Details',itemRows,[10,30,30,20,20,12,14,10,12,30]);
 sheet(wb,'Refunds',refunds.map(r=>({Order:r.order_number,Refunded_At:r.at,Type:r.kind||'full',Amount_USD:Number(r.amount_cents||0)/100,Refund_USD:Number(r.payment?.usd_cents||0)/100,Refund_LBP:Number(r.payment?.lbp||0),Cashier:r.user,Reason:r.reason,Items:(r.items||[]).map(i=>`${i.quantity}x ${i.name_en||i.name_ar}`).join(', ')})),[10,23,14,14,14,16,20,30,50]);
 sheet(wb,'Expenses',(ledger.expenses||[]).map(e=>({Date:e.date||e.created_at,Category:e.category,Amount:e.amount,Currency:e.currency,Paid_From:e.paid_from,Note:e.note,Created_By:e.created_by})),[16,20,14,12,18,35,20]);
 sheet(wb,'Shifts',(ledger.shifts||[]).map(s=>({Cashier:s.user_name,Opened:s.opened_at,Closed:s.closed_at||'',Opening_USD:s.opening_usd,Opening_LBP:s.opening_lbp,Expected_USD:s.expected_usd,Expected_LBP:s.expected_lbp,Counted_USD:s.closing_usd,Counted_LBP:s.closing_lbp,Variance_USD:s.variance_usd,Variance_LBP:s.variance_lbp,Status:s.status})),[20,23,23,14,16,14,16,14,16,14,16,12]);
 sheet(wb,'Inventory',(state.inventory||[]).map(i=>({Item:i.name,Category:i.category,Quantity:i.quantity,Unit:i.unit,Minimum:i.minimum,Unit_Cost_USD:i.unit_cost,Stock_Value_USD:Number(i.quantity||0)*Number(i.unit_cost||0),Low_Stock:Number(i.minimum||0)>0&&Number(i.quantity)<=Number(i.minimum)?'YES':'NO'})),[30,20,14,12,14,16,18,12]);
 sheet(wb,'Audit',(state.audit||[]).filter(a=>inFinancePeriod(a.at,'daily',anchor)).map(a=>({At:a.at,Action:a.type,User:a.user||'',Order:a.order_id||'',Reason:a.reason||'',Amount_USD:a.amount_cents!=null?Number(a.amount_cents)/100:'',Details:a.items?JSON.stringify(a.items):''})),[23,25,20,20,35,14,50]);return {buffer:XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),filename:`Cocktaillo-Daily-Report-${date}.xlsx`,ledger}}
