export const dessertSubcategories=['Crepe','Waffle','Pancake','Cold Dessert','Ice Cream','Merry Cream'];
const rows=[
 ['crepe-chocolate','Crepe - Chocolate','كريب - شوكولا','Crepe',500,true],
 ['waffle-chocolate','Waffle - Chocolate','وافل - شوكولا','Waffle',600,true],
 ['pancake6-chocolate','Pancake 6 pcs - Chocolate','بان كيك ٦ قطع - شوكولا','Pancake',350,true],
 ['pancake12-chocolate','Pancake 12 pcs - Chocolate','بان كيك ١٢ قطعة - شوكولا','Pancake',700,true],
 ['crepe-nutella','Crepe - Nutella','كريب - نوتيلا','Crepe',600,true],
 ['waffle-nutella','Waffle - Nutella','وافل - نوتيلا','Waffle',700,true],
 ['pancake6-nutella','Pancake 6 pcs - Nutella','بان كيك ٦ قطع - نوتيلا','Pancake',400,true],
 ['pancake12-nutella','Pancake 12 pcs - Nutella','بان كيك ١٢ قطعة - نوتيلا','Pancake',800,true],
 ['crepe-lotus','Crepe - Lotus','كريب - لوتس','Crepe',600,true],
 ['waffle-lotus','Waffle - Lotus','وافل - لوتس','Waffle',700,true],
 ['pancake6-lotus','Pancake 6 pcs - Lotus','بان كيك ٦ قطع - لوتس','Pancake',400,true],
 ['pancake12-lotus','Pancake 12 pcs - Lotus','بان كيك ١٢ قطعة - لوتس','Pancake',800,true],
 ['crepe-white-chocolate','Crepe - White Chocolate','كريب - شوكولا بيضاء','Crepe',600,true],
 ['waffle-white-chocolate','Waffle - White Chocolate','وافل - شوكولا بيضاء','Waffle',700,true],
 ['pancake6-white-chocolate','Pancake 6 pcs - White Chocolate','بان كيك ٦ قطع - شوكولا بيضاء','Pancake',400,true],
 ['pancake12-white-chocolate','Pancake 12 pcs - White Chocolate','بان كيك ١٢ قطعة - شوكولا بيضاء','Pancake',800,true],
 ['crepe-dark-chocolate','Crepe - Dark Chocolate','كريب - شوكولا داكنة','Crepe',500,true],
 ['waffle-dark-chocolate','Waffle - Dark Chocolate','وافل - شوكولا داكنة','Waffle',600,true],
 ['pancake6-dark-chocolate','Pancake 6 pcs - Dark Chocolate','بان كيك ٦ قطع - شوكولا داكنة','Pancake',350,true],
 ['pancake12-dark-chocolate','Pancake 12 pcs - Dark Chocolate','بان كيك ١٢ قطعة - شوكولا داكنة','Pancake',700,true],
 ['crepe-kinder','Crepe - Kinder','كريب - كيندر','Crepe',600,true],
 ['waffle-kinder','Waffle - Kinder','وافل - كيندر','Waffle',700,true],
 ['pancake6-kinder','Pancake 6 pcs - Kinder','بان كيك ٦ قطع - كيندر','Pancake',400,true],
 ['pancake12-kinder','Pancake 12 pcs - Kinder','بان كيك ١٢ قطعة - كيندر','Pancake',800,true],
 ['crepe-oreo','Crepe - Oreo','كريب - أوريو','Crepe',600,true],
 ['waffle-oreo','Waffle - Oreo','وافل - أوريو','Waffle',700,true],
 ['pancake6-oreo','Pancake 6 pcs - Oreo','بان كيك ٦ قطع - أوريو','Pancake',400,true],
 ['pancake12-oreo','Pancake 12 pcs - Oreo','بان كيك ١٢ قطعة - أوريو','Pancake',800,true],
 ['crepe-marshmallow','Crepe - Marshmallow','كريب - مارشميلو','Crepe',600,true],
 ['waffle-marshmallow','Waffle - Marshmallow','وافل - مارشميلو','Waffle',700,true],
 ['pancake6-marshmallow','Pancake 6 pcs - Marshmallow','بان كيك ٦ قطع - مارشميلو','Pancake',400,true],
 ['pancake12-marshmallow','Pancake 12 pcs - Marshmallow','بان كيك ١٢ قطعة - مارشميلو','Pancake',800,true],
 ['crepe-pistachio','Crepe - Pistachio','كريب - فستق','Crepe',700,true],
 ['waffle-pistachio','Waffle - Pistachio','وافل - فستق','Waffle',800,true],
 ['pancake6-pistachio','Pancake 6 pcs - Pistachio','بان كيك ٦ قطع - فستق','Pancake',450,true],
 ['pancake12-pistachio','Pancake 12 pcs - Pistachio','بان كيك ١٢ قطعة - فستق','Pancake',900,true],
 ['crepe-belgian-chocolate','Crepe - Belgian Chocolate','كريب - شوكولا بلجيكية','Crepe',700,true],
 ['waffle-belgian-chocolate','Waffle - Belgian Chocolate','وافل - شوكولا بلجيكية','Waffle',800,true],
 ['pancake6-belgian-chocolate','Pancake 6 pcs - Belgian Chocolate','بان كيك ٦ قطع - شوكولا بلجيكية','Pancake',450,true],
 ['pancake12-belgian-chocolate','Pancake 12 pcs - Belgian Chocolate','بان كيك ١٢ قطعة - شوكولا بلجيكية','Pancake',900,true],
 ['crepe-ferrero','Crepe - Ferrero','كريب - فيريرو','Crepe',700,true],
 ['waffle-ferrero','Waffle - Ferrero','وافل - فيريرو','Waffle',800,true],
 ['pancake6-ferrero','Pancake 6 pcs - Ferrero','بان كيك ٦ قطع - فيريرو','Pancake',450,true],
 ['pancake12-ferrero','Pancake 12 pcs - Ferrero','بان كيك ١٢ قطعة - فيريرو','Pancake',900,true],
 ['pancake12-mix','Pancake 12 pcs - Mix','بان كيك ١٢ قطعة - ميكس','Pancake',1000,true],
 ['crepe-fettuccine','Fettuccine Crepe','كريب فيتوتشيني','Crepe',1200,true],
 ['crepe-sushi','Sushi Crepe','كريب سوشي','Crepe',800,true],
 ['crepe-roll','Roll Crepe','رول كريب','Crepe',800,true],
 ['cold-jelly','Jelly','جيلي','Cold Dessert',100,false],
 ['cold-moghli','Moghli','مغلي','Cold Dessert',188,false],
 ['cold-rice-pudding','Rice Pudding','رز بحليب','Cold Dessert',188,false],
 ['cold-custard','Custard','كاسترد','Cold Dessert',188,false],
 ['cold-knafeh','Knafeh','كنافة','Cold Dessert',388,false],
 ['cold-chocolate-mousse','Chocolate Mousse','موس شوكولا','Cold Dessert',633,false],
 ['icecream-kg','Ice Cream 1 kg','آيس كريم ١ كغ','Ice Cream',1800,false],
 ['icecream-half','Ice Cream 1/2 kg','آيس كريم نصف كغ','Ice Cream',900,false],
 ['icecream-ball','Ice Cream 1 Ball','آيس كريم كرة واحدة','Ice Cream',111,false],
 ['merry-cream','Merry Cream','ميري كريم','Merry Cream',200,false]
];
export const dessertMenu=rows.map(([id,name_en,name_ar,subcategory,price_cents,allow_addons],i)=>({id,name_en,name_ar,category:'Dessert',subcategory,price_cents,station:'bar',allow_addons,available:true,sort_order:i+1}));
export const dessertAddons=[
 ['nutella','Nutella','نوتيلا',100000],['lotus','Lotus','لوتس',100000],['icecream','Ice Cream','آيس كريم',100000],['milka','Milka','ميلكا',100000],['white-chocolate','White Chocolate','شوكولا بيضاء',100000],['kinder','Kinder','كيندر',100000],['oreo','Oreo','أوريو',100000],['marshmallow','Marshmallow','مارشميلو',100000],['caramel','Caramel','كراميل',100000],['banana','Banana','موز',80000],['strawberry','Strawberry','فراولة',80000],['pineapple','Pineapple','أناناس',80000],['mango','Mango','مانغا',80000],['nuts','Nuts','مكسرات',80000],['kiwi','Kiwi','كيوي',80000],['cotton-candy','Cotton Candy','غزل البنات',80000]
].map(([id,name_en,name_ar,price_lbp])=>({id,name_en,name_ar,price_lbp,available:true}));