import {netTender} from './cash.js';
import {orderCost,orderTotal} from './store.js';
import {refundedQuantity} from './refunds.js';
const validDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d};
export function inFinancePeriod(value,period='all',anchor=new Date()){if(period==='all')return true;const d=validDate(value),a=validDate(anchor);if(!d||!a)return false;if(period==='daily')return d.getFullYear()===a.getFullYear()&&d.getMonth()===a.getMonth()&&d.getDate()===a.getDate();if(period==='monthly')return d.getFullYear()===a.getFullYear()&&d.getMonth()===a.getMonth();if(period==='yearly')return d.getFullYear()===a.getFullYear();return true}
const receiptFor=(s,o)=>(s.receipts||[]).find(r=>r.order_id===o.id)||null;
const saleCents=(s,o,r)=>Number(receiptFor(s,o)?.totals?.total_equivalent_cents??orderTotal(o,r).total_equivalent_cents??0);
const subtotalCents=(s,o,r)=>Number(receiptFor(s,o)?.totals?.subtotal_equivalent_cents??orderTotal(o,r).subtotal_equivalent_cents??0);
const discountCents=(s,o,r)=>Number(receiptFor(s,o)?.totals?.discount_cents??orderTotal(o,r).discount_cents??0);
const cogsUsd=(s,o)=>Number(o.financial_snapshot?.cogs_usd??receiptFor(s,o)?.cogs_usd??orderCost(s,o)??0);
const orderDate=o=>o.paid_at||o.updated_at||o.created_at;
function refundedCogs(s,refund){const order=s.orders.find(o=>o.id===refund.order_id);if(!order)return 0;return (refund.items||[]).reduce((sum,item)=>{const line=order.lines.find(l=>l.id===item.line_id);if(!line)return sum;const fullLineCost=orderCost(s,{lines:[{...line,quantity:1}]});return sum+fullLineCost*Number(item.quantity||0)},0)}
export function financeLedger(state,{period='all',anchor=new Date()}={}){const rate=Number(state.settings?.exchange_rate||89500),settled=(state.orders||[]).filter(o=>['paid','partially_refunded','refunded'].includes(o.status)&&inFinancePeriod(orderDate(o),period,anchor)),refunds=(state.refunds||[]).filter(r=>inFinancePeriod(r.at,period,anchor)),expenses=(state.expenses||[]).filter(e=>inFinancePeriod(e.date||e.created_at,period,anchor)),purchases=(state.purchases||[]).filter(p=>inFinancePeriod(p.date||p.created_at,period,anchor)),shifts=(state.shifts||[]).filter(s=>inFinancePeriod(s.opened_at,period,anchor));
 const grossSalesCents=settled.reduce((sum,o)=>sum+saleCents(state,o,rate),0),refundsCents=refunds.reduce((sum,r)=>sum+Number(r.amount_cents||0),0),netSalesCents=grossSalesCents-refundsCents,subtotal=settled.reduce((sum,o)=>sum+subtotalCents(state,o,rate),0),discounts=settled.reduce((sum,o)=>sum+discountCents(state,o,rate),0),grossCogs=settled.reduce((sum,o)=>sum+cogsUsd(state,o),0),returnedCogs=refunds.reduce((sum,r)=>sum+refundedCogs(state,r),0),cogs=Math.max(0,grossCogs-returnedCogs),expenseUsd=expenses.reduce((sum,e)=>sum+(String(e.currency).toUpperCase()==='LBP'?Number(e.amount||0)/rate:Number(e.amount||0)),0),grossProfit=netSalesCents/100-cogs,netProfit=grossProfit-expenseUsd;
 let paidUsd=0,paidLbp=0,refundedUsd=0,refundedLbp=0;for(const o of settled){const p=netTender(receiptFor(state,o)||{payment:o.payments?.[0]});paidUsd+=Number(p.usd_cents||0)/100;paidLbp+=Number(p.lbp||0)}for(const r of refunds){refundedUsd+=Number(r.payment?.usd_cents||0)/100;refundedLbp+=Number(r.payment?.lbp||0)}const inventoryValue=(state.inventory||[]).reduce((sum,i)=>sum+Number(i.quantity||0)*Number(i.unit_cost||0),0),purchaseUsd=purchases.reduce((sum,p)=>sum+Number(p.total_cost||0),0);return {period,anchor:new Date(anchor).toISOString(),exchange_rate:rate,gross_sales_cents:grossSalesCents,refunds_cents:refundsCents,net_sales_cents:netSalesCents,subtotal_cents:subtotal,discounts_cents:discounts,orders:settled.length,paid_orders:settled.filter(o=>o.status!=='refunded').length,refunded_orders:new Set(refunds.map(r=>r.order_id)).size,average_order_usd:settled.length?grossSalesCents/100/settled.length:0,cogs_usd:cogs,gross_profit_usd:grossProfit,expenses_usd:expenseUsd,net_profit_usd:netProfit,gross_margin_percent:netSalesCents?grossProfit/(netSalesCents/100)*100:0,paid_usd:paidUsd,paid_lbp:paidLbp,refunded_usd:refundedUsd,refunded_lbp:refundedLbp,net_cash_usd:paidUsd-refundedUsd,net_cash_lbp:paidLbp-refundedLbp,inventory_value_usd:inventoryValue,purchases_usd:purchaseUsd,expenses,purchases,shifts,refunds,recovered_orders:[],recovered_refunds:[]}}
