import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import bcrypt from 'bcryptjs';
import { beverageMenu, beverageCategories, beverageSubcategories } from './beverage-seed.js';

const file = process.env.POS_DATA_FILE || path.join(process.cwd(), '.data', 'cocktaillo.json');
let queue = Promise.resolve();
const dessertMenu = [
 ['crepe-chocolate','Crepe - Chocolate','كريب - شوكولا','Crepe',500,'bar',true],['crepe-nutella','Crepe - Nutella','كريب - نوتيلا','Crepe',600,'bar',true],['crepe-lotus','Crepe - Lotus','كريب - لوتس','Crepe',600,'bar',true],['waffle-chocolate','Waffle - Chocolate','وافل - شوكولا','Waffle',600,'bar',true],['waffle-nutella','Waffle - Nutella','وافل - نوتيلا','Waffle',700,'bar',true],['pancake6-chocolate','Pancake 6 pcs - Chocolate','بان كيك ٦ قطع - شوكولا','Pancake',350,'bar',true],['pancake12-chocolate','Pancake 12 pcs - Chocolate','بان كيك ١٢ قطعة - شوكولا','Pancake',700,'bar',true],['cold-jelly','Jelly','جيلي','Cold Dessert',100,'bar',false],['cold-rice-pudding','Rice Pudding','رز بحليب','Cold Dessert',188,'bar',false],['cold-knafeh','Knafeh','كنافة','Cold Dessert',388,'bar',false],['icecream-ball','Ice Cream 1 ball','آيس كريم كرة واحدة','Ice Cream',111,'bar',false],['icecream-half','Ice Cream 1/2 kg','آيس كريم نصف كغ','Ice Cream',900,'bar',false],['icecream-kg','Ice Cream 1 kg','آيس كريم ١ كغ','Ice Cream',1800,'bar',false]
].map(([id,name_en,name_ar,subcategory,price_cents,station,allow_addons],i)=>({id,name_en,name_ar,category:'Dessert',subcategory,price_cents,station,allow_addons,available:true,sort_order:i+1}));
const extraMenu = [
 ['salad-fruit','Fruit Salad','سلطة فواكه','Salads',600,'bar'],
 ['salad-fruit-nutella','Fruit Salad with Nutella','سلطة فواكه مع نوتيلا','Salads',700,'bar'],
 ['salad-fruit-nuts','Fruit Salad with Nuts','سلطة فواكه مع مكسرات','Salads',700,'bar'],
 ['salad-fruit-cream-honey-nuts','Fruit Salad with Cream, Honey & Nuts','سلطة فواكه مع قشطة وعسل ومكسرات','Salads',800,'bar'],
 ['hookah-two-apples-fakher','Two Apples - Fakher','تفاحتين - فاخر','Hookah',700,'bar'],
 ['hookah-two-apples-nakhla','Two Apples - Nakhla','تفاحتين - نخلة','Hookah',700,'bar'],
 ['hookah-two-apples-mix','Two Apples - Mix','تفاحتين - ميكس','Hookah',700,'bar'],
 ['hookah-lemon-mint','Lemon & Mint','ليمون ونعنع','Hookah',700,'bar'],
 ['hookah-grape-mint','Grape & Mint','عنب ونعنع','Hookah',700,'bar'],
 ['hookah-love','Love','لوف','Hookah',700,'bar'],
 ['hookah-head-change','Head Change','تغيير راس','Hookah',388,'bar']
].map(([id,name_en,name_ar,category,price_cents,station],i)=>({id,name_en,name_ar,category,subcategory:'',price_cents,station,allow_addons:false,available:true,sort_order:500+i}));
const menu=[...dessertMenu,...beverageMenu,...extraMenu];
const addons=[['nutella','Nutella','نوتيلا',100000],['lotus','Lotus','لوتس',100000],['icecream','Ice Cream','آيس كريم',100000],['milka','Milka','ميلكا',100000],['white-chocolate','White Chocolate','شوكولا بيضاء',100000],['kinder','Kinder','كيندر',100000],['oreo','Oreo','أوريو',100000],['marshmallow','Marshmallow','مارشميلو',100000],['caramel','Caramel','كراميل',100000],['banana','Banana','موز',80000],['strawberry','Strawberry','فراولة',80000],['pineapple','Pineapple','أناناس',80000],['mango','Mango','مانغا',80000],['nuts','Nuts','مكسرات',80000],['kiwi','Kiwi','كيوي',80000],['cotton-candy','Cotton Candy','غزل البنات',80000]].map(([id,name_en,name_ar,price_lbp])=>({id,name_en,name_ar,price_lbp,available:true}));
async function initialState(){const passwordManager=await bcrypt.hash('2300',10),passwordCashier=await bcrypt.hash('1234',10),passwordWaiter=await bcrypt.hash('12345678',10);return {version:4,users:[{id:'u-manager',name:'Alex Daher',username:'manager',password_hash:passwordManager,role:'manager',active:true},{id:'u-cashier',name:'Jamie D.',username:'cashier',password_hash:passwordCashier,role:'cashier',active:true},{id:'u-waiter',name:'Waiter',username:'waiter',password_hash:passwordWaiter,role:'waiter',active:true}],settings:{business_name:'Cocktaillo',exchange_rate:89500,receipt_footer:'Thank you for visiting Cocktaillo',language:'en',theme:'light'},tables:Array.from({length:12},(_,i)=>({id:`table-${i+1}`,name:`Table ${i+1}`,capacity:[2,4,4,2,6,4,2,8,4,2,4,6][i],status:'available'})),categories:['Dessert',...beverageCategories,'Salads','Hookah'],subcategories:['Crepe','Waffle','Pancake','Cold Dessert','Ice Cream',...beverageSubcategories],menu,addons,shifts:[],orders:[],receipts:[],tickets:[],inventory:[],recipes:[],expenses:[],reservations:[],audit:[],next_order_number:1}}
function migrate(state){state.version=4;for(const k of ['receipts','recipes','inventory','expenses','reservations','audit'])state[k]=Array.isArray(state[k])?state[k]:[];state.settings={business_name:'Cocktaillo',exchange_rate:89500,receipt_footer:'Thank you for visiting Cocktaillo',language:'en',theme:'light',...(state.settings||{})};state.categories=Array.from(new Set(['Dessert',...beverageCategories,'Salads','Hookah',...(state.categories||[]).filter(x=>!['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream'].includes(x))]));state.subcategories=Array.from(new Set(['Crepe','Waffle','Pancake','Cold Dessert','Ice Cream',...beverageSubcategories,...(state.subcategories||[])]));state.menu=(state.menu||[]).map(i=>{if(['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream'].includes(i.category))return {...i,category:'Dessert',subcategory:i.category==='Pancakes'?'Pancake':i.category};return {...i,subcategory:i.subcategory||''}});const ids=new Set(state.menu.map(i=>i.id));for(const item of [...beverageMenu,...extraMenu])if(!ids.has(item.id)){state.menu.push({...item});ids.add(item.id)}return state}
async function readUnlocked(){try{return migrate(JSON.parse(await readFile(file,'utf8')))}catch{const state=await initialState();await writeUnlocked(state);return state}}
async function writeUnlocked(state){await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await writeFile(tmp,JSON.stringify(state,null,2));await rename(tmp,file)}
export async function readState(){return readUnlocked()}
export async function mutateState(fn){let resolve,reject;const result=new Promise((r,j)=>{resolve=r;reject=j});queue=queue.then(async()=>{try{const state=await readUnlocked();const value=await fn(state);await writeUnlocked(state);resolve(value)}catch(e){reject(e)}},async()=>{try{const state=await readUnlocked();const value=await fn(state);await writeUnlocked(state);resolve(value)}catch(e){reject(e)}});return result}
export const publicUser=u=>({id:u.id,name:u.name,username:u.username,role:u.role,active:u.active});
export const orderTotal=(order,rate=89500)=>{const usd=order.lines.reduce((s,l)=>s+l.price_cents*l.quantity,0);const lbp=order.lines.reduce((s,l)=>s+l.addons.reduce((a,x)=>a+x.price_lbp*x.quantity*l.quantity,0),0);return {usd_cents:usd,lbp,total_equivalent_cents:usd+Math.round((lbp/rate)*100)}};
export function recipeCost(state,menuItemId){const recipe=state.recipes.find(r=>r.menu_item_id===menuItemId);return (recipe?.lines||[]).reduce((sum,l)=>{const inv=state.inventory.find(i=>i.id===l.inventory_id);return sum+Number(l.quantity||0)*Number(inv?.unit_cost||0)},0)}
export function orderCost(state,order){return order.lines.reduce((sum,l)=>sum+recipeCost(state,l.menu_item_id)*Number(l.quantity||0),0)}
export function deductRecipes(state,order){for(const line of order.lines){const recipe=state.recipes.find(r=>r.menu_item_id===line.menu_item_id);if(!recipe)continue;for(const component of recipe.lines||[]){const stock=state.inventory.find(i=>i.id===component.inventory_id);if(stock)stock.quantity=Number(stock.quantity||0)-Number(component.quantity||0)*line.quantity}}}
