import { mkdir, readFile, rename, writeFile, access, open, unlink, stat } from 'node:fs/promises';
import path from 'node:path';
import bcrypt from 'bcryptjs';
import { beverageMenu, beverageCategories, beverageSubcategories } from './beverage-seed.js';
import { dessertMenu, dessertSubcategories, dessertAddons } from './dessert-seed.js';

const file = process.env.POS_DATA_FILE || path.join(process.cwd(), '.data', 'cocktaillo.json');
const backupDir=path.join(path.dirname(file),'backups');
const lockFile=`${file}.lock`;
let queue = Promise.resolve();
const extraMenu = [
 ['salad-fruit','Fruit Salad','سلطة فواكه','Salads',600,'bar'],['salad-fruit-nutella','Fruit Salad with Nutella','سلطة فواكه مع نوتيلا','Salads',700,'bar'],['salad-fruit-nuts','Fruit Salad with Nuts','سلطة فواكه مع مكسرات','Salads',700,'bar'],['salad-fruit-cream-honey-nuts','Fruit Salad with Cream, Honey & Nuts','سلطة فواكه مع قشطة وعسل ومكسرات','Salads',800,'bar'],['hookah-two-apples-fakher','Two Apples - Fakher','تفاحتين - فاخر','Hookah',700,'bar'],['hookah-two-apples-nakhla','Two Apples - Nakhla','تفاحتين - نخلة','Hookah',700,'bar'],['hookah-two-apples-mix','Two Apples - Mix','تفاحتين - ميكس','Hookah',700,'bar'],['hookah-lemon-mint','Lemon & Mint','ليمون ونعنع','Hookah',700,'bar'],['hookah-grape-mint','Grape & Mint','عنب ونعنع','Hookah',700,'bar'],['hookah-love','Love','لوف','Hookah',700,'bar'],['hookah-head-change','Head Change','تغيير راس','Hookah',388,'bar']
].map(([id,name_en,name_ar,category,price_cents,station],i)=>({id,name_en,name_ar,category,subcategory:'',price_cents,station,allow_addons:false,available:true,sort_order:500+i}));
const menu=[...dessertMenu,...beverageMenu,...extraMenu];
const addons=dessertAddons;
const defaultSettings={business_name:'Cocktaillo',exchange_rate:89500,receipt_footer:'Thank you for visiting Cocktaillo',language:'en',theme:'light',print_agent_url:'http://127.0.0.1:17483',customer_printer_name:'Customer Receipt',kitchen_printer_name:'Kitchen Printer',bar_printer_name:'Bar Printer'};
function firstBootManagerPassword(){const configured=String(process.env.POS_INITIAL_MANAGER_PASSWORD||'');if(configured){const minimum=process.env.NODE_ENV==='production'?8:4;if(configured.length<minimum)throw new Error(`POS_INITIAL_MANAGER_PASSWORD must be at least ${minimum} characters.`);return configured}if(process.env.NODE_ENV==='production')throw new Error('POS data file is missing. Set POS_INITIAL_MANAGER_PASSWORD before the first production boot.');return '2300'}
async function initialState(){const passwordManager=await bcrypt.hash(firstBootManagerPassword(),10);return {version:9,users:[{id:'u-manager',name:'Alex Daher',username:'manager',password_hash:passwordManager,role:'manager',active:true}],settings:{...defaultSettings},tables:Array.from({length:12},(_,i)=>({id:`table-${i+1}`,name:`Table ${i+1}`,capacity:[2,4,4,2,6,4,2,8,4,2,4,6][i],status:'available'})),categories:['Dessert',...beverageCategories,'Salads','Hookah'],subcategories:[...dessertSubcategories,...beverageSubcategories],menu,addons,shifts:[],orders:[],receipts:[],tickets:[],print_jobs:[],inventory:[],recipes:[],expenses:[],purchases:[],refunds:[],reservations:[],audit:[],next_order_number:1}}
function migrate(state){const oldVersion=Number(state.version||0);state.version=9;for(const k of ['receipts','recipes','inventory','expenses','purchases','refunds','reservations','audit','print_jobs'])state[k]=Array.isArray(state[k])?state[k]:[];state.users=Array.isArray(state.users)?state.users:[];if(oldVersion<7){const manager=state.users.find(u=>u.role==='manager')||state.users[0];state.users=manager?[{...manager,role:'manager',active:true}]:[]}state.settings={...defaultSettings,...(state.settings||{})};state.categories=Array.from(new Set(['Dessert',...beverageCategories,'Salads','Hookah',...(state.categories||[]).filter(x=>!['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream','Merry Cream'].includes(x))]));state.subcategories=Array.from(new Set([...dessertSubcategories,...beverageSubcategories,...(state.subcategories||[])]));state.menu=(state.menu||[]).map(i=>{if(['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream','Merry Cream'].includes(i.category))return {...i,category:'Dessert',subcategory:i.category==='Pancakes'?'Pancake':i.category};return {...i,subcategory:i.subcategory||''}});const incoming=[...dessertMenu,...beverageMenu,...extraMenu];const byId=new Map(state.menu.map(i=>[i.id,i]));for(const item of incoming){const current=byId.get(item.id);if(current)Object.assign(current,{...item,available:current.available!==false});else{state.menu.push({...item});byId.set(item.id,item)}}const addonById=new Map((state.addons||[]).map(a=>[a.id,a]));for(const addon of dessertAddons){const current=addonById.get(addon.id);if(current)Object.assign(current,{...addon,available:current.available!==false});else{state.addons.push({...addon});addonById.set(addon.id,addon)}}return state}
async function readUnlocked(){let raw;try{raw=await readFile(file,'utf8')}catch(e){if(e?.code!=='ENOENT')throw e;const state=await initialState();await writeUnlocked(state);return state}let parsed;try{parsed=JSON.parse(raw)}catch(e){throw new Error(`POS data file is not valid JSON: ${file}`,{cause:e})}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error(`POS data file has an invalid root structure: ${file}`);return migrate(parsed)}
async function writeDailySnapshot(state){try{await mkdir(backupDir,{recursive:true});const day=new Date().toISOString().slice(0,10),target=path.join(backupDir,`cocktaillo-auto-${day}.json`);try{await access(target);return}catch{}await writeFile(target,JSON.stringify({format:'cocktaillo-pos-auto-backup',created_at:new Date().toISOString(),data:state},null,2))}catch(e){console.warn('[Cocktaillo] Automatic backup snapshot failed:',e instanceof Error?e.message:e)}}
async function writeUnlocked(state){await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await writeFile(tmp,JSON.stringify(state,null,2));await rename(tmp,file)}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function acquireFileLock(){await mkdir(path.dirname(file),{recursive:true});const started=Date.now();while(true){try{const handle=await open(lockFile,'wx');await handle.writeFile(`${process.pid}:${Date.now()}`);return async()=>{try{await handle.close()}finally{await unlink(lockFile).catch(e=>{if(e?.code!=='ENOENT')throw e})}}}catch(e){if(e?.code!=='EEXIST')throw e;try{const info=await stat(lockFile);if(Date.now()-info.mtimeMs>30000){await unlink(lockFile).catch(err=>{if(err?.code!=='ENOENT')throw err});continue}}catch(err){if(err?.code==='ENOENT')continue;throw err}if(Date.now()-started>=10000)throw new Error('POS data file is busy. Please retry the operation.');await wait(50)}}}
export async function readState(){return readUnlocked()}
async function runMutation(fn){const release=await acquireFileLock();try{const state=await readUnlocked();await writeDailySnapshot(state);const value=await fn(state);await writeUnlocked(state);return value}finally{await release()}}
export async function mutateState(fn){const run=()=>runMutation(fn);const result=queue.then(run,run);queue=result.catch(()=>{});return result}
export const publicUser=u=>({id:u.id,name:u.name,username:u.username,role:u.role,active:u.active});
export const publicSettings=s=>{const {manager_pin_hash,...safe}=s||{};return safe};
export const orderTotal=(order,rate=89500)=>{const exchangeRate=Number(rate);if(!Number.isFinite(exchangeRate)||exchangeRate<=0)throw new Error('Exchange rate must be a positive number.');const usd=order.lines.reduce((s,l)=>s+l.price_cents*l.quantity,0);const lbp=order.lines.reduce((s,l)=>s+l.addons.reduce((a,x)=>a+x.price_lbp*x.quantity*l.quantity,0),0);const before=usd+Math.round((lbp/exchangeRate)*100);const d=order.discount||null;let discount_cents=0;if(d?.type==='percent')discount_cents=Math.round(before*Math.min(100,Math.max(0,Number(d.value||0)))/100);if(d?.type==='fixed')discount_cents=Math.min(before,Math.round(Math.max(0,Number(d.value||0))*100));return {usd_cents:usd,lbp,subtotal_equivalent_cents:before,discount_cents,total_equivalent_cents:Math.max(0,before-discount_cents)}};
export function recipeCost(state,menuItemId){const recipe=state.recipes.find(r=>r.menu_item_id===menuItemId);return (recipe?.lines||[]).reduce((sum,l)=>{const inv=state.inventory.find(i=>i.id===l.inventory_id);return sum+Number(l.quantity||0)*Number(inv?.unit_cost||0)},0)}
export function orderCost(state,order){return order.lines.reduce((sum,l)=>sum+recipeCost(state,l.menu_item_id)*Number(l.quantity||0),0)}
export function deductRecipes(state,order){for(const line of order.lines){const recipe=state.recipes.find(r=>r.menu_item_id===line.menu_item_id);if(!recipe)continue;for(const component of recipe.lines||[]){const stock=state.inventory.find(i=>i.id===component.inventory_id);if(stock)stock.quantity=Number(stock.quantity||0)-Number(component.quantity||0)*line.quantity}}}
export function restoreRecipes(state,order){for(const line of order.lines){const recipe=state.recipes.find(r=>r.menu_item_id===line.menu_item_id);if(!recipe)continue;for(const component of recipe.lines||[]){const stock=state.inventory.find(i=>i.id===component.inventory_id);if(stock)stock.quantity=Number(stock.quantity||0)+Number(component.quantity||0)*line.quantity}}}
