import { mkdir, readFile, rename, writeFile, access } from 'node:fs/promises';
import path from 'node:path';
import bcrypt from 'bcryptjs';
import { beverageMenu, beverageCategories, beverageSubcategories } from './beverage-seed.js';
import { dessertMenu, dessertSubcategories, dessertAddons } from './dessert-seed.js';

const file = process.env.POS_DATA_FILE || path.join(process.cwd(), '.data', 'cocktaillo.json');
const backupDir=path.join(path.dirname(file),'backups');
let queue = Promise.resolve();
const extraMenu = [
 ['salad-fruit','Fruit Salad','سلطة فواكه','Salads',600,'bar'],['salad-fruit-nutella','Fruit Salad with Nutella','سلطة فواكه مع نوتيلا','Salads',700,'bar'],['salad-fruit-nuts','Fruit Salad with Nuts','سلطة فواكه مع مكسرات','Salads',700,'bar'],['salad-fruit-cream-honey-nuts','Fruit Salad with Cream, Honey & Nuts','سلطة فواكه مع قشطة وعسل ومكسرات','Salads',800,'bar'],['hookah-two-apples-fakher','Two Apples - Fakher','تفاحتين - فاخر','Hookah',700,'bar'],['hookah-two-apples-nakhla','Two Apples - Nakhla','تفاحتين - نخلة','Hookah',700,'bar'],['hookah-two-apples-mix','Two Apples - Mix','تفاحتين - ميكس','Hookah',700,'bar'],['hookah-lemon-mint','Lemon & Mint','ليمون ونعنع','Hookah',700,'bar'],['hookah-grape-mint','Grape & Mint','عنب ونعنع','Hookah',700,'bar'],['hookah-love','Love','لوف','Hookah',700,'bar'],['hookah-head-change','Head Change','تغيير راس','Hookah',388,'bar']
].map(([id,name_en,name_ar,category,price_cents,station],i)=>({id,name_en,name_ar,category,subcategory:'',price_cents,station,allow_addons:false,available:true,sort_order:500+i}));
const menu=[...dessertMenu,...beverageMenu,...extraMenu];
const addons=dessertAddons;
async function initialState(){const passwordManager=await bcrypt.hash('2300',10);return {version:8,users:[{id:'u-manager',name:'Alex Daher',username:'manager',password_hash:passwordManager,role:'manager',active:true}],settings:{business_name:'Cocktaillo',exchange_rate:89500,receipt_footer:'Thank you for visiting Cocktaillo',language:'en',theme:'light'},tables:Array.from({length:12},(_,i)=>({id:`table-${i+1}`,name:`Table ${i+1}`,capacity:[2,4,4,2,6,4,2,8,4,2,4,6][i],status:'available'})),categories:['Dessert',...beverageCategories,'Salads','Hookah'],subcategories:[...dessertSubcategories,...beverageSubcategories],menu,addons,shifts:[],orders:[],receipts:[],tickets:[],inventory:[],recipes:[],expenses:[],purchases:[],refunds:[],reservations:[],audit:[],next_order_number:1}}
function migrate(state){const oldVersion=Number(state.version||0);state.version=8;for(const k of ['receipts','recipes','inventory','expenses','purchases','refunds','reservations','audit'])state[k]=Array.isArray(state[k])?state[k]:[];state.users=Array.isArray(state.users)?state.users:[];if(oldVersion<7){const manager=state.users.find(u=>u.role==='manager')||state.users[0];state.users=manager?[{...manager,role:'manager',active:true}]:[]}state.settings={business_name:'Cocktaillo',exchange_rate:89500,receipt_footer:'Thank you for visiting Cocktaillo',language:'en',theme:'light',...(state.settings||{})};state.categories=Array.from(new Set(['Dessert',...beverageCategories,'Salads','Hookah',...(state.categories||[]).filter(x=>!['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream','Merry Cream'].includes(x))]));state.subcategories=Array.from(new Set([...dessertSubcategories,...beverageSubcategories,...(state.subcategories||[])]));state.menu=(state.menu||[]).map(i=>{if(['Crepe','Waffle','Pancakes','Pancake','Cold Dessert','Ice Cream','Merry Cream'].includes(i.category))return {...i,category:'Dessert',subcategory:i.category==='Pancakes'?'Pancake':i.category};return {...i,subcategory:i.subcategory||''}});const incoming=[...dessertMenu,...beverageMenu,...extraMenu];const byId=new Map(state.menu.map(i=>[i.id,i]));for(const item of incoming){const current=byId.get(item.id);if(current)Object.assign(current,{...item,available:current.available!==false});else{state.menu.push({...item});byId.set(item.id,item)}}const addonById=new Map((state.addons||[]).map(a=>[a.id,a]));for(const addon of dessertAddons){const current=addonById.get(addon.id);if(current)Object.assign(current,{...addon,available:current.available!==false});else{state.addons.push({...addon});addonById.set(addon.id,addon)}}return state}
async function readUnlocked(){try{return migrate(JSON.parse(await readFile(file,'utf8')))}catch{const state=await initialState();await writeUnlocked(state);return state}}
async function writeDailySnapshot(state){try{await mkdir(backupDir,{recursive:true});const day=new Date().toISOString().slice(0,10),target=path.join(backupDir,`cocktaillo-auto-${day}.json`);try{await access(target);return}catch{}await writeFile(target,JSON.stringify({format:'cocktaillo-pos-auto-backup',created_at:new Date().toISOString(),data:state},null,2))}catch{}}
async function writeUnlocked(state){await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await writeFile(tmp,JSON.stringify(state,null,2));await rename(tmp,file)}
export async function readState(){return readUnlocked()}
export async function mutateState(fn){let resolve,reject;const result=new Promise((r,j)=>{resolve=r;reject=j});queue=queue.then(async()=>{try{const state=await readUnlocked();await writeDailySnapshot(state);const value=await fn(state);await writeUnlocked(state);resolve(value)}catch(e){reject(e)}},async()=>{try{const state=await readUnlocked();await writeDailySnapshot(state);const value=await fn(state);await writeUnlocked(state);resolve(value)}catch(e){reject(e)}});return result}
export const publicUser=u=>({id:u.id,name:u.name,username:u.username,role:u.role,active:u.active});
export const publicSettings=s=>{const {manager_pin_hash,...safe}=s||{};return safe};
export const orderTotal=(order,rate=89500)=>{const usd=order.lines.reduce((s,l)=>s+l.price_cents*l.quantity,0);const lbp=order.lines.reduce((s,l)=>s+l.addons.reduce((a,x)=>a+x.price_lbp*x.quantity*l.quantity,0),0);const before=usd+Math.round((lbp/rate)*100);const d=order.discount||null;let discount_cents=0;if(d?.type==='percent')discount_cents=Math.round(before*Math.min(100,Math.max(0,Number(d.value||0)))/100);if(d?.type==='fixed')discount_cents=Math.min(before,Math.round(Math.max(0,Number(d.value||0))*100));return {usd_cents:usd,lbp,subtotal_equivalent_cents:before,discount_cents,total_equivalent_cents:Math.max(0,before-discount_cents)}};
export function recipeCost(state,menuItemId){const recipe=state.recipes.find(r=>r.menu_item_id===menuItemId);return (recipe?.lines||[]).reduce((sum,l)=>{const inv=state.inventory.find(i=>i.id===l.inventory_id);return sum+Number(l.quantity||0)*Number(inv?.unit_cost||0)},0)}
export function orderCost(state,order){return order.lines.reduce((sum,l)=>sum+recipeCost(state,l.menu_item_id)*Number(l.quantity||0),0)}
export function deductRecipes(state,order){for(const line of order.lines){const recipe=state.recipes.find(r=>r.menu_item_id===line.menu_item_id);if(!recipe)continue;for(const component of recipe.lines||[]){const stock=state.inventory.find(i=>i.id===component.inventory_id);if(stock)stock.quantity=Number(stock.quantity||0)-Number(component.quantity||0)*line.quantity}}}
export function restoreRecipes(state,order){for(const line of order.lines){const recipe=state.recipes.find(r=>r.menu_item_id===line.menu_item_id);if(!recipe)continue;for(const component of recipe.lines||[]){const stock=state.inventory.find(i=>i.id===component.inventory_id);if(stock)stock.quantity=Number(stock.quantity||0)+Number(component.quantity||0)*line.quantity}}}
