'use client';
import {useState} from 'react';
export default function ReportView({report:r}){
  const [ar,setAr]=useState(true),t=(en,arabic)=>ar?arabic:en,money=n=>`$${(Number(n||0)/100).toFixed(2)}`;
  const cashLabels={opening:['Opening','الافتتاح'],tender:['Received','المقبوض'],change:['Change given','الباقي المدفوع'],refund:['Refunds paid','المردود المدفوع'],expense:['Drawer expenses','مصاريف الصندوق'],expected:['Expected','المتوقّع'],counted:['Counted','المعدود'],variance:['Variance','الفرق']};
  return <main dir={ar?'rtl':'ltr'} style={{maxWidth:900,margin:'auto',padding:20}}>
    <nav style={{display:'flex',gap:12,alignItems:'center'}}><a href="/">COCKTAILLO</a><button className="btn btnSoft" onClick={()=>setAr(!ar)}>{ar?'English':'العربية'}</button></nav>
    <h1>{t('Shift closing report','تقرير إقفال الشيفت')}</h1><strong>{r.cashier}</strong><p>{r.opened_at} — {r.closed_at}</p><small>{r.shift_id}</small>
    <p><a className="btn btnPrimary" href={`/api/shift-report?shift_id=${encodeURIComponent(r.shift_id)}&format=xlsx`}>{t('Download full Excel report','تنزيل تقرير Excel الكامل')}</a></p>
    <section className="card section"><h2>{t('Sales','المبيعات')}</h2><p>{t('Orders','الطلبات')}: {r.order_count}</p><p>{t('Gross','الإجمالي قبل الحسم')}: {money(r.gross_total_cents)}</p><p>{t('Discounts','الحسومات')}: {money(r.discount_total_cents)}</p><p>{t('Refunds','المردودات')}: {money(r.refund_total_cents)}</p><strong>{t('Net sales (not profit)','صافي المبيعات (مش الأرباح)')}: {money(r.net_total_cents)}</strong></section>
    <section className="card section"><h2>{t('Cash reconciliation','مطابقة الصندوق')}</h2><table style={{width:'100%',textAlign:'start'}}><thead><tr><th>{t('Entry','البند')}</th><th>USD</th><th>LBP</th></tr></thead><tbody>{Object.entries(cashLabels).map(([k,labels])=><tr key={k}><td>{t(...labels)}</td><td>{money(r.cash[`${k}_usd_cents`])}</td><td>{r.cash[`${k}_lbp`].toLocaleString()}</td></tr>)}</tbody></table></section>
    <h2>{t('Paid orders','الطلبات المدفوعة')}</h2>{r.receipts.map(o=><section className="card section" key={o.id}><strong>#{o.number} · {o.table_name||o.type} · {money(o.totals.total_equivalent_cents)}</strong>{(o.items||[]).map((l,i)=><p key={i}>{l.quantity} × {ar?(l.name_ar||l.name_en):l.name_en} · {money(l.price_cents)}{(l.addons||[]).map((a,n)=><small style={{display:'block'}} key={n}>+ {a.quantity} × {ar?(a.name_ar||a.name_en):a.name_en} · {a.price_lbp} LBP</small>)}{l.note&&<small style={{display:'block'}}>{t('Note','ملاحظة')}: {l.note}</small>}</p>)}<small>{t('Discount','الحسم')}: {money(o.totals.discount_cents)} · {t('Received','المقبوض')}: {money(o.payment.usd_cents)} / {o.payment.lbp||0} LBP · {t('Change','الباقي')}: {money(o.change_payment.usd_cents)} / {o.change_payment.lbp} LBP</small></section>)}
    <section className="card section"><h2>{t('Refunds and drawer expenses','المردودات ومصاريف الصندوق')}</h2>{r.refunds.map(f=><p key={f.id}>#{f.order_number} · {money(f.amount_cents)} · {f.reason}</p>)}{r.expenses.map(e=><p key={e.id}>{e.amount} {e.currency} · {e.category} · {e.note}</p>)}</section>
    <section className="card section"><h2>{t('Item counts','جردة الأصناف')}</h2>{r.item_counts.map(i=><p key={i.item_id}>{ar?(i.name_ar||i.name_en):i.name_en}: {t('Sold','مباع')} {i.sold} · {t('Returned','مرتجع')} {i.refunded}</p>)}</section>
    <section className="card section"><h2>{t('Recorded stock at close','المخزون المسجّل عند الإقفال')}</h2><p>{t('These are system quantities, not a physical stock count.','هيدي كميات النظام، مش جردة فعلية للموجود بالمحل.')}</p>{r.inventory.map((i,n)=><p key={i.id||n}>{i.name}: {i.quantity} {i.unit}</p>)}</section>
    {r.warnings.length>0&&<section className="error"><h2>{t('Review required','بحاجة للمراجعة')}</h2>{r.warnings.map(w=><p key={w}>{w}</p>)}</section>}
  </main>
}
