const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const ROOT=__dirname,CONFIG=path.join(ROOT,'config.json'),LOG=path.join(ROOT,'print-jobs.json');
function parseJsonFile(p,fallback={}){try{return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}catch{return fallback}}
function loadConfig(){if(fs.existsSync(CONFIG))return parseJsonFile(CONFIG,{});const c={port:17483,token:crypto.randomBytes(32).toString('hex'),allowed_origins:['https://indigo-ape-952022.hostingersite.com','http://localhost:3000'],printers:{customer:'Customer Receipt',kitchen:'Kitchen Printer',bar:'Bar Printer',hookah:'HOOKAH'}};fs.writeFileSync(CONFIG,JSON.stringify(c,null,2));return c}
const config=loadConfig();let jobs=fs.existsSync(LOG)?parseJsonFile(LOG,{}):{};let queue=Promise.resolve();
function saveJobs(){fs.writeFileSync(LOG,JSON.stringify(jobs,null,2))}
function cors(req,res){const o=req.headers.origin||'';if(o&&config.allowed_origins.includes(o))res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Private-Network','true')}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function auth(req){const o=req.headers.origin||'';if(o&&!config.allowed_origins.includes(o))return false;return req.headers.authorization===`Bearer ${config.token}`}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1024*1024){reject(new Error('Payload too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
const {receiptEscpos}=require('./print-layout.js');
const {renderArabicTicket}=require('./arabic-ticket.js');
function psPrint(printer,buffer){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(ROOT,'print-raw.ps1'),'-PrinterName',printer],{windowsHide:true,stdio:['pipe','ignore','pipe']});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(err||`PowerShell exited ${code}`)));p.stdin.on('error',e=>{if(e.code!=='EPIPE')reject(e)});p.stdin.end(buffer.toString('base64'))})}
function listPrinters(){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command','Get-Printer | Select-Object -ExpandProperty Name | ConvertTo-Json -Compress'],{windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',code=>{if(code!==0)return reject(new Error(err||'Could not enumerate printers'));try{const v=JSON.parse(out||'[]');resolve(Array.isArray(v)?v:[v].filter(Boolean))}catch(e){reject(e)}})})}
async function handlePrint(b){if(!b.job_id)throw new Error('job_id required');if(jobs[b.job_id]?.status==='printed')return {ok:true,already_printed:true,job:jobs[b.job_id]};const destination=b.destination==='bar'?'bar':b.destination==='hookah'?'hookah':b.destination==='customer'?'customer':null;if(!destination)throw new Error('Unsupported print destination');const printer=String(b.printer_name||config.printers?.[destination]||'');if(!printer)throw new Error('Printer not configured');const available=await listPrinters();if(!available.includes(printer))throw new Error('Windows printer not found: '+printer);jobs[b.job_id]={job_id:b.job_id,destination,printer,status:'printing',attempts:Number(jobs[b.job_id]?.attempts||0)+1,updated_at:new Date().toISOString()};saveJobs();try{const payload=(destination==='bar'||destination==='hookah')?await renderArabicTicket(b.ticket||{}):receiptEscpos(b.receipt||{},{openDrawer:destination==='customer'&&b.open_drawer===true});await psPrint(printer,payload);jobs[b.job_id]={...jobs[b.job_id],status:'printed',printed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null};saveJobs();return {ok:true,job:jobs[b.job_id]}}catch(e){jobs[b.job_id]={...jobs[b.job_id],status:'failed',last_error:e.message,updated_at:new Date().toISOString()};saveJobs();throw e}}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(!auth(req))return json(res,401,{error:'Unauthorized print agent request'});try{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,name:'Cocktaillo Windows Print Agent',version:'2.5.0'});if(req.method==='GET'&&req.url==='/printers')return json(res,200,{printers:await listPrinters()});if(req.method==='POST'&&req.url==='/print'){const b=await body(req);const result=await(queue=queue.then(()=>handlePrint(b),()=>handlePrint(b)));return json(res,200,result)}return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:e.message||'Print agent error'})}});
server.listen(Number(config.port||17483),'127.0.0.1',()=>{console.log(`Cocktaillo Print Agent listening on http://127.0.0.1:${config.port||17483}`);console.log(`Pairing token: ${config.token}`);console.log(`Customer printer: ${config.printers?.customer||'Customer Receipt'}`);console.log(`Bar printer: ${config.printers?.bar||'Bar Printer'}`);console.log(`Hookah printer: ${config.printers?.hookah||'HOOKAH'}`)});
