const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const ROOT=__dirname,CONFIG=path.join(ROOT,'config.json'),LOG=path.join(ROOT,'print-jobs.json');
function loadConfig(){if(fs.existsSync(CONFIG))return JSON.parse(fs.readFileSync(CONFIG,'utf8'));const c={port:17483,token:crypto.randomBytes(32).toString('hex'),allowed_origins:['https://steelblue-giraffe-156727.hostingersite.com','http://localhost:3000'],printers:{customer:'Customer Receipt',kitchen:'Kitchen Printer',bar:'Bar Printer'}};fs.writeFileSync(CONFIG,JSON.stringify(c,null,2));return c}
const config=loadConfig();let jobs=fs.existsSync(LOG)?JSON.parse(fs.readFileSync(LOG,'utf8')):{};let queue=Promise.resolve();
function saveJobs(){fs.writeFileSync(LOG,JSON.stringify(jobs,null,2))}
function cors(req,res){const o=req.headers.origin||'';if(o&&config.allowed_origins.includes(o))res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Private-Network','true')}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function auth(req){const o=req.headers.origin||'';if(o&&!config.allowed_origins.includes(o))return false;return req.headers.authorization===`Bearer ${config.token}`}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1024*1024){reject(new Error('Payload too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function clean(s){return String(s??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'').trim()}
const W=42;function line(a='',b=''){a=clean(a);b=clean(b);if(!b)return a.slice(0,W);const room=Math.max(1,W-b.length-1);return `${a.slice(0,room)}${' '.repeat(Math.max(1,W-Math.min(room,a.length)-b.length))}${b.slice(-W)}`.slice(0,W)}
function money(c){return `$${(Number(c||0)/100).toFixed(2)}`}
function escpos(r){const chunks=[],txt=s=>chunks.push(Buffer.from(String(s),'ascii'));chunks.push(Buffer.from([0x1b,0x40]));chunks.push(Buffer.from([0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11]));txt('COCKTAILLO\n');chunks.push(Buffer.from([0x1d,0x21,0x00,0x1b,0x45,0x00]));txt(`Receipt #${r.order_number}\n`);if(r.table)txt(`${clean(r.table)}\n`);txt(`${new Date(r.created_at).toLocaleString('en-GB')}\n`);chunks.push(Buffer.from([0x1b,0x61,0x00]));txt('-'.repeat(W)+'\n');for(const i of r.items||[]){txt(line(`${i.quantity} x ${i.name}`,money(i.line_total_cents))+'\n');for(const a of i.addons||[])txt(line(`  + ${a.name} x${a.quantity}`,`${Number(a.price_lbp||0).toLocaleString()} LBP`)+'\n')}txt('-'.repeat(W)+'\n');txt(line('Subtotal',money(r.subtotal_cents))+'\n');if(r.discount_cents)txt(line('Discount',`-${money(r.discount_cents)}`)+'\n');chunks.push(Buffer.from([0x1b,0x45,0x01]));txt(line('TOTAL',money(r.total_cents))+'\n');chunks.push(Buffer.from([0x1b,0x45,0x00]));txt(line('Payment',r.payment_method)+'\n');if(r.paid_usd_cents)txt(line('Paid USD',money(r.paid_usd_cents))+'\n');if(r.paid_lbp)txt(line('Paid LBP',`${Number(r.paid_lbp).toLocaleString()} LBP`)+'\n');if(r.change_cents)txt(line('CHANGE',money(r.change_cents))+'\n');txt(line('Cashier',r.cashier||'')+'\n');txt('-'.repeat(W)+'\n');chunks.push(Buffer.from([0x1b,0x61,0x01]));if(r.footer)txt(clean(r.footer).slice(0,W)+'\n');txt('Thank you\n');chunks.push(Buffer.from([0x1b,0x64,0x05,0x1d,0x56,0x00]));return Buffer.concat(chunks)}
function psPrint(printer,buffer){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(ROOT,'print-raw.ps1'),'-PrinterName',printer,'-Base64',buffer.toString('base64')],{windowsHide:true});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(err||`PowerShell exited ${code}`)))})}
function listPrinters(){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command','Get-Printer | Select-Object -ExpandProperty Name | ConvertTo-Json -Compress'],{windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',code=>{if(code!==0)return reject(new Error(err||'Could not enumerate printers'));try{const v=JSON.parse(out||'[]');resolve(Array.isArray(v)?v:[v].filter(Boolean))}catch(e){reject(e)}})})}
async function handlePrint(b){if(!b.job_id)throw new Error('job_id required');if(jobs[b.job_id]?.status==='printed')return {ok:true,already_printed:true,job:jobs[b.job_id]};const printer=String(b.printer_name||config.printers?.[b.destination]||'');if(!printer)throw new Error('Printer not configured');const available=await listPrinters();if(!available.includes(printer))throw new Error(`Windows printer not found: ${printer}`);jobs[b.job_id]={job_id:b.job_id,destination:b.destination||'customer',printer,status:'printing',attempts:Number(jobs[b.job_id]?.attempts||0)+1,updated_at:new Date().toISOString()};saveJobs();try{await psPrint(printer,escpos(b.receipt||{}));jobs[b.job_id]={...jobs[b.job_id],status:'printed',printed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null};saveJobs();return {ok:true,job:jobs[b.job_id]}}catch(e){jobs[b.job_id]={...jobs[b.job_id],status:'failed',last_error:e.message,updated_at:new Date().toISOString()};saveJobs();throw e}}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(!auth(req))return json(res,401,{error:'Unauthorized print agent request'});try{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,name:'Cocktaillo Windows Print Agent',version:'1.0.0'});if(req.method==='GET'&&req.url==='/printers')return json(res,200,{printers:await listPrinters()});if(req.method==='POST'&&req.url==='/print'){const b=await body(req);const result=await(queue=queue.then(()=>handlePrint(b),()=>handlePrint(b)));return json(res,200,result)}return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:e.message||'Print agent error'})}});
server.listen(Number(config.port||17483),'127.0.0.1',()=>{console.log(`Cocktaillo Print Agent listening on http://127.0.0.1:${config.port||17483}`);console.log(`Pairing token: ${config.token}`);console.log(`Customer printer: ${config.printers?.customer||'Customer Receipt'}`)});
