const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{spawn}=require('child_process');
const APP='CocktailloPrintAgent';
const LOCAL=process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local');
const APPDIR=path.join(LOCAL,APP),CONFIG=path.join(APPDIR,'config.json'),LOG=path.join(APPDIR,'print-jobs.json');
const INSTALLED_EXE=path.join(APPDIR,'CocktailloPrintAgent.exe');
const STARTUP=path.join(process.env.APPDATA||path.join(os.homedir(),'AppData','Roaming'),'Microsoft','Windows','Start Menu','Programs','Startup','CocktailloPrintAgent.cmd');
function parse(p,f={}){try{return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}catch{return f}}
function initialConfig(){return {port:17483,token:crypto.randomBytes(32).toString('hex'),allowed_origins:['https://indigo-ape-952022.hostingersite.com','http://localhost:3000'],printers:{customer:'Customer Receipt',kitchen:'Kitchen Printer',bar:'Bar Printer',hookah:'HOOKAH'}}}
function ensureConfig(){fs.mkdirSync(APPDIR,{recursive:true});const defaults=initialConfig();if(!fs.existsSync(CONFIG)){fs.writeFileSync(CONFIG,JSON.stringify(defaults,null,2));return defaults}const saved=parse(CONFIG,{}),merged={...defaults,...saved,printers:{...defaults.printers,...(saved.printers||{})}};if(JSON.stringify(saved)!==JSON.stringify(merged))fs.writeFileSync(CONFIG,JSON.stringify(merged,null,2));return merged}
function openToken(config){try{const desktop=path.join(os.homedir(),'Desktop');const p=path.join(desktop,'Cocktaillo Printer Pairing Token.txt');fs.writeFileSync(p,`COCKTAILLO PRINTER AGENT\r\n\r\nPairing token:\r\n${config.token}\r\n\r\nAgent URL:\r\nhttp://127.0.0.1:${config.port}\r\n\r\nCustomer printer:\r\n${config.printers.customer}\r\n\r\nBar printer:\r\n${config.printers.bar}\r\n\r\nHookah printer:\r\n${config.printers.hookah||'HOOKAH'}\r\n\r\nCopy the pairing token into Cocktaillo POS > Settings > Cashier Computer Printers.\r\n`);spawn('notepad.exe',[p],{detached:true,stdio:'ignore'}).unref()}catch{}}
function psQuote(v){return `'${String(v).replace(/'/g,"''")}'`}
function install(){const config=ensureConfig();
 try{fs.mkdirSync(path.dirname(STARTUP),{recursive:true});fs.writeFileSync(STARTUP,`@echo off\r\nstart \"\" \"${INSTALLED_EXE}\" --run\r\n`)}catch(e){console.error('Startup registration failed:',e.message)}
 openToken(config);
 const source=process.execPath;
 const same=path.resolve(source).toLowerCase()===path.resolve(INSTALLED_EXE).toLowerCase();
 try{
  if(same){spawn(INSTALLED_EXE,['--run'],{detached:true,stdio:'ignore'}).unref()}
  else{
   const script=`Start-Sleep -Seconds 2; New-Item -ItemType Directory -Force -Path ${psQuote(APPDIR)} | Out-Null; Copy-Item -LiteralPath ${psQuote(source)} -Destination ${psQuote(INSTALLED_EXE)} -Force; Start-Process -FilePath ${psQuote(INSTALLED_EXE)} -ArgumentList '--run'`;
   spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',script],{detached:true,stdio:'ignore',windowsHide:true}).unref();
  }
 }catch(e){console.error('Install launch failed:',e.message);process.exit(1)}
 console.log('Cocktaillo Print Agent installation scheduled. Pairing token opened in Notepad.');
 console.log('The agent will start automatically in about 2 seconds.');
 setTimeout(()=>process.exit(0),500)}
function uninstall(){try{fs.unlinkSync(STARTUP)}catch{};try{fs.rmSync(APPDIR,{recursive:true,force:true})}catch{};console.log('Cocktaillo Print Agent removed.');setTimeout(()=>process.exit(0),800)}
if(process.platform!=='win32'){console.error('This print agent is for Windows only.');process.exit(1)}
const args=process.argv.slice(2);if(args.includes('--uninstall'))return uninstall();if(!args.includes('--run'))return install();
const config=ensureConfig();let jobs=fs.existsSync(LOG)?parse(LOG,{}):{},queue=Promise.resolve();
function saveJobs(){try{fs.writeFileSync(LOG,JSON.stringify(jobs,null,2))}catch{}}
function cors(req,res){const o=req.headers.origin||'';if(o&&config.allowed_origins.includes(o))res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Private-Network','true')}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function auth(req){const o=req.headers.origin||'';if(o&&!config.allowed_origins.includes(o))return false;return req.headers.authorization===`Bearer ${config.token}`}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1024*1024){reject(new Error('Payload too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
const {receiptEscpos}=require('./print-layout.js');
const {renderArabicTicket}=require('./arabic-ticket.js');
function encodedPs(script){return Buffer.from(script,'utf16le').toString('base64')}
function psPrint(printer,buffer){const cs=`using System;using System.Runtime.InteropServices;public class R{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public class D{[MarshalAs(UnmanagedType.LPWStr)]public string pDocName;[MarshalAs(UnmanagedType.LPWStr)]public string pOutputFile;[MarshalAs(UnmanagedType.LPWStr)]public string pDataType;}[DllImport("winspool.Drv",EntryPoint="OpenPrinterW",SetLastError=true,CharSet=CharSet.Unicode)]public static extern bool O(string n,out IntPtr h,IntPtr d);[DllImport("winspool.Drv",EntryPoint="ClosePrinter",SetLastError=true)]public static extern bool C(IntPtr h);[DllImport("winspool.Drv",EntryPoint="StartDocPrinterW",SetLastError=true,CharSet=CharSet.Unicode)]public static extern bool S(IntPtr h,int l,[In]D d);[DllImport("winspool.Drv",EntryPoint="EndDocPrinter",SetLastError=true)]public static extern bool E(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool StartPagePrinter(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool EndPagePrinter(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool WritePrinter(IntPtr h,IntPtr p,int c,out int w);}`;const script=`$ErrorActionPreference='Stop';Add-Type -TypeDefinition @'\n${cs}\n'@;$b=[Convert]::FromBase64String([Console]::In.ReadToEnd());$h=[IntPtr]::Zero;if(-not [R]::O('${String(printer).replace(/'/g,"''")}',[ref]$h,[IntPtr]::Zero)){throw 'OpenPrinter failed'};try{$d=New-Object R+D;$d.pDocName='Cocktaillo Receipt';$d.pDataType='RAW';if(-not [R]::S($h,1,$d)){throw 'StartDoc failed'};[R]::StartPagePrinter($h)|Out-Null;$p=[Runtime.InteropServices.Marshal]::AllocHGlobal($b.Length);try{[Runtime.InteropServices.Marshal]::Copy($b,0,$p,$b.Length);$w=0;if(-not [R]::WritePrinter($h,$p,$b.Length,[ref]$w)){throw 'WritePrinter failed'}}finally{[Runtime.InteropServices.Marshal]::FreeHGlobal($p)};[R]::EndPagePrinter($h)|Out-Null;[R]::E($h)|Out-Null}finally{[R]::C($h)|Out-Null}`;return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-EncodedCommand',encodedPs(script)],{windowsHide:true,stdio:['pipe','ignore','pipe']});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(err||`PowerShell exited ${c}`)));p.stdin.on('error',e=>{if(e.code!=='EPIPE')reject(e)});p.stdin.end(buffer.toString('base64'))})}
function listPrinters(){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command','Get-Printer | Select-Object -ExpandProperty Name | ConvertTo-Json -Compress'],{windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',c=>{if(c!==0)return reject(new Error(err||'Could not enumerate printers'));try{const v=JSON.parse(out||'[]');resolve(Array.isArray(v)?v:[v].filter(Boolean))}catch(e){reject(e)}})})}
async function handlePrint(b){if(!b.job_id)throw new Error('job_id required');if(jobs[b.job_id]?.status==='printed')return {ok:true,already_printed:true,job:jobs[b.job_id]};const destination=b.destination==='bar'?'bar':b.destination==='hookah'?'hookah':b.destination==='customer'?'customer':null;if(!destination)throw new Error('Unsupported print destination');const printer=String(b.printer_name||config.printers?.[destination]||'');if(!printer)throw new Error('Printer not configured');const available=await listPrinters();if(!available.includes(printer))throw new Error('Windows printer not found: '+printer);jobs[b.job_id]={job_id:b.job_id,destination,printer,status:'printing',attempts:Number(jobs[b.job_id]?.attempts||0)+1,updated_at:new Date().toISOString()};saveJobs();try{const payload=(destination==='bar'||destination==='hookah')?await renderArabicTicket(b.ticket||{}):receiptEscpos(b.receipt||{},{openDrawer:destination==='customer'&&b.open_drawer===true});await psPrint(printer,payload);jobs[b.job_id]={...jobs[b.job_id],status:'printed',printed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null};saveJobs();return {ok:true,job:jobs[b.job_id]}}catch(e){jobs[b.job_id]={...jobs[b.job_id],status:'failed',last_error:e.message,updated_at:new Date().toISOString()};saveJobs();throw e}}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(!auth(req))return json(res,401,{error:'Unauthorized print agent request'});try{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,name:'Cocktaillo Windows Print Agent',version:'2.5.0'});if(req.method==='GET'&&req.url==='/printers')return json(res,200,{printers:await listPrinters()});if(req.method==='POST'&&req.url==='/print'){const b=await body(req),result=await(queue=queue.then(()=>handlePrint(b),()=>handlePrint(b)));return json(res,200,result)}return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:e.message||'Print agent error'})}});server.listen(Number(config.port||17483),'127.0.0.1',()=>console.log(`Cocktaillo Print Agent running on 127.0.0.1:${config.port||17483}`));
