const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{spawn}=require('child_process');
const APP='CocktailloPrintAgent';
const LOCAL=process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local');
const APPDIR=path.join(LOCAL,APP),CONFIG=path.join(APPDIR,'config.json'),LOG=path.join(APPDIR,'print-jobs.json');
const INSTALLED_EXE=path.join(APPDIR,'CocktailloPrintAgent.exe');
const STARTUP=path.join(process.env.APPDATA||path.join(os.homedir(),'AppData','Roaming'),'Microsoft','Windows','Start Menu','Programs','Startup','CocktailloPrintAgent.cmd');
function parse(p,f={}){try{return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}catch{return f}}
function initialConfig(){return {port:17483,token:crypto.randomBytes(32).toString('hex'),allowed_origins:['https://steelblue-giraffe-156727.hostingersite.com','http://localhost:3000'],printers:{customer:'Customer Receipt',kitchen:'Kitchen Printer',bar:'Bar Printer'}}}
function ensureConfig(){fs.mkdirSync(APPDIR,{recursive:true});if(!fs.existsSync(CONFIG))fs.writeFileSync(CONFIG,JSON.stringify(initialConfig(),null,2));return parse(CONFIG,initialConfig())}
function openToken(config){try{const desktop=path.join(os.homedir(),'Desktop');const p=path.join(desktop,'Cocktaillo Printer Pairing Token.txt');fs.writeFileSync(p,`COCKTAILLO PRINTER AGENT\r\n\r\nPairing token:\r\n${config.token}\r\n\r\nAgent URL:\r\nhttp://127.0.0.1:${config.port}\r\n\r\nCustomer printer:\r\n${config.printers.customer}\r\n\r\nCopy the pairing token into Cocktaillo POS > Settings > Customer Receipt Printer.\r\n`);spawn('notepad.exe',[p],{detached:true,stdio:'ignore'}).unref()}catch{}}
function psQuote(v){return `'${String(v).replace(/'/g,"''")}'`}
function install(){const config=ensureConfig();
 try{fs.mkdirSync(path.dirname(STARTUP),{recursive:true});fs.writeFileSync(STARTUP,`@echo off\r\nstart \"\" \"${INSTALLED_EXE}\" --run\r\n`)}catch(e){console.error('Startup registration failed:',e.message)}
 openToken(config);
 const source=process.execPath;
 const same=path.resolve(source).toLowerCase()===path.resolve(INSTALLED_EXE).toLowerCase();
 try{
  if(same){spawn(INSTALLED_EXE,['--run'],{detached:true,stdio:'ignore'}).unref()}
  else{
   const script=`Start-Sleep -Seconds 2; New-Item -ItemType Directory -Force -Path ${psQuote(APPDIR)} | Out-Null; Copy-Item -LiteralPath ${psQuote(source)} -Destination ${psQuote(INSTALLED_EXE)} -Force; Start-Process -FilePath ${psQuote(INSTALLED_EXE)} -ArgumentList '--run'`;
   spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',script],{detached:true,stdio:'ignore',windowsHide:true}).unref();
  }
 }catch(e){console.error('Install launch failed:',e.message);process.exit(1)}
 console.log('Cocktaillo Print Agent installation scheduled. Pairing token opened in Notepad.');
 console.log('The agent will start automatically in about 2 seconds.');
 setTimeout(()=>process.exit(0),500)}
function uninstall(){try{fs.unlinkSync(STARTUP)}catch{};try{fs.rmSync(APPDIR,{recursive:true,force:true})}catch{};console.log('Cocktaillo Print Agent removed.');setTimeout(()=>process.exit(0),800)}
if(process.platform!=='win32'){console.error('This print agent is for Windows only.');process.exit(1)}
const args=process.argv.slice(2);if(args.includes('--uninstall'))return uninstall();if(!args.includes('--run'))return install();
const config=ensureConfig();let jobs=fs.existsSync(LOG)?parse(LOG,{}):{},queue=Promise.resolve();
function saveJobs(){try{fs.writeFileSync(LOG,JSON.stringify(jobs,null,2))}catch{}}
function cors(req,res){const o=req.headers.origin||'';if(o&&config.allowed_origins.includes(o))res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Private-Network','true')}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function auth(req){const o=req.headers.origin||'';if(o&&!config.allowed_origins.includes(o))return false;return req.headers.authorization===`Bearer ${config.token}`}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1024*1024){reject(new Error('Payload too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function clean(s){return String(s??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'').trim()}
const W=42;function line(a='',b=''){a=clean(a);b=clean(b);if(!b)return a.slice(0,W);const room=Math.max(1,W-b.length-1);return `${a.slice(0,room)}${' '.repeat(Math.max(1,W-Math.min(room,a.length)-b.length))}${b.slice(-W)}`.slice(0,W)}function money(c){return `$${(Number(c||0)/100).toFixed(2)}`}
function qrCommands(value){const data=Buffer.from(String(value||''),'utf8'),len=data.length+3,pL=len&255,pH=(len>>8)&255;return Buffer.concat([Buffer.from([0x1d,0x28,0x6b,0x04,0x00,0x31,0x41,0x32,0x00]),Buffer.from([0x1d,0x28,0x6b,0x03,0x00,0x31,0x43,0x05]),Buffer.from([0x1d,0x28,0x6b,0x03,0x00,0x31,0x45,0x31]),Buffer.from([0x1d,0x28,0x6b,pL,pH,0x31,0x50,0x30]),data,Buffer.from([0x1d,0x28,0x6b,0x03,0x00,0x31,0x51,0x30])])}
function escpos(r){const chunks=[],txt=s=>chunks.push(Buffer.from(String(s),'ascii'));chunks.push(Buffer.from([0x1b,0x40,0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11]));txt('COCKTAILLO\n');chunks.push(Buffer.from([0x1d,0x21,0x00,0x1b,0x45,0x00]));txt(`Receipt #${r.order_number}\n`);if(r.table)txt(`${clean(r.table)}\n`);txt(`${new Date(r.created_at).toLocaleString('en-GB')}\n`);chunks.push(Buffer.from([0x1b,0x61,0x00]));txt('-'.repeat(W)+'\n');for(const i of r.items||[]){txt(line(`${i.quantity} x ${i.name}`,money(i.line_total_cents))+'\n');for(const a of i.addons||[])txt(line(`  + ${a.name} x${a.quantity}`,`${Number(a.price_lbp||0).toLocaleString()} LBP`)+'\n')}txt('-'.repeat(W)+'\n');txt(line('Subtotal',money(r.subtotal_cents))+'\n');if(r.discount_cents)txt(line('Discount',`-${money(r.discount_cents)}`)+'\n');chunks.push(Buffer.from([0x1b,0x45,0x01]));txt(line('TOTAL',money(r.total_cents))+'\n');chunks.push(Buffer.from([0x1b,0x45,0x00]));txt(line('Payment',r.payment_method)+'\n');if(r.paid_usd_cents)txt(line('Paid USD',money(r.paid_usd_cents))+'\n');if(r.paid_lbp)txt(line('Paid LBP',`${Number(r.paid_lbp).toLocaleString()} LBP`)+'\n');if(r.change_cents)txt(line('CHANGE',money(r.change_cents))+'\n');txt(line('Cashier',r.cashier||'')+'\n');txt('-'.repeat(W)+'\n');chunks.push(Buffer.from([0x1b,0x61,0x01]));if(r.footer)txt(clean(r.footer).slice(0,W)+'\n');if(r.instagram_url){txt('Follow us on Instagram\n');chunks.push(qrCommands(r.instagram_url));txt('\n'+clean(r.instagram_handle||'@cocktaillorestocafe')+'\n')}txt('Thank you\n');chunks.push(Buffer.from([0x1b,0x64,0x05,0x1d,0x56,0x00]));return Buffer.concat(chunks)}
function encodedPs(script){return Buffer.from(script,'utf16le').toString('base64')}
function psPrint(printer,buffer){const cs=`using System;using System.Runtime.InteropServices;public class R{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public class D{[MarshalAs(UnmanagedType.LPWStr)]public string pDocName;[MarshalAs(UnmanagedType.LPWStr)]public string pOutputFile;[MarshalAs(UnmanagedType.LPWStr)]public string pDataType;}[DllImport("winspool.Drv",EntryPoint="OpenPrinterW",SetLastError=true,CharSet=CharSet.Unicode)]public static extern bool O(string n,out IntPtr h,IntPtr d);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool C(IntPtr h);[DllImport("winspool.Drv",EntryPoint="StartDocPrinterW",SetLastError=true,CharSet=CharSet.Unicode)]public static extern bool S(IntPtr h,int l,[In]D d);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool E(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool StartPagePrinter(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool EndPagePrinter(IntPtr h);[DllImport("winspool.Drv",SetLastError=true)]public static extern bool WritePrinter(IntPtr h,IntPtr p,int c,out int w);}`;const script=`$ErrorActionPreference='Stop';Add-Type -TypeDefinition @'\n${cs}\n'@;$b=[Convert]::FromBase64String('${buffer.toString('base64')}');$h=[IntPtr]::Zero;if(-not [R]::O('${String(printer).replace(/'/g,"''")}',[ref]$h,[IntPtr]::Zero)){throw 'OpenPrinter failed'};try{$d=New-Object R+D;$d.pDocName='Cocktaillo Receipt';$d.pDataType='RAW';if(-not [R]::S($h,1,$d)){throw 'StartDoc failed'};[R]::StartPagePrinter($h)|Out-Null;$p=[Runtime.InteropServices.Marshal]::AllocHGlobal($b.Length);try{[Runtime.InteropServices.Marshal]::Copy($b,0,$p,$b.Length);$w=0;if(-not [R]::WritePrinter($h,$p,$b.Length,[ref]$w)){throw 'WritePrinter failed'}}finally{[Runtime.InteropServices.Marshal]::FreeHGlobal($p)};[R]::EndPagePrinter($h)|Out-Null;[R]::E($h)|Out-Null}finally{[R]::C($h)|Out-Null}`;return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-EncodedCommand',encodedPs(script)],{windowsHide:true});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(err||`PowerShell exited ${c}`)))})}
function listPrinters(){return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command','Get-Printer | Select-Object -ExpandProperty Name | ConvertTo-Json -Compress'],{windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',c=>{if(c!==0)return reject(new Error(err||'Could not enumerate printers'));try{const v=JSON.parse(out||'[]');resolve(Array.isArray(v)?v:[v].filter(Boolean))}catch(e){reject(e)}})})}
async function handlePrint(b){if(!b.job_id)throw new Error('job_id required');if(jobs[b.job_id]?.status==='printed')return {ok:true,already_printed:true,job:jobs[b.job_id]};const printer=String(b.printer_name||config.printers?.[b.destination]||'');if(!printer)throw new Error('Printer not configured');const available=await listPrinters();if(!available.includes(printer))throw new Error(`Windows printer not found: ${printer}`);jobs[b.job_id]={job_id:b.job_id,destination:b.destination||'customer',printer,status:'printing',attempts:Number(jobs[b.job_id]?.attempts||0)+1,updated_at:new Date().toISOString()};saveJobs();try{await psPrint(printer,escpos(b.receipt||{}));jobs[b.job_id]={...jobs[b.job_id],status:'printed',printed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null};saveJobs();return {ok:true,job:jobs[b.job_id]}}catch(e){jobs[b.job_id]={...jobs[b.job_id],status:'failed',last_error:e.message,updated_at:new Date().toISOString()};saveJobs();throw e}}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(!auth(req))return json(res,401,{error:'Unauthorized print agent request'});try{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,name:'Cocktaillo Windows Print Agent',version:'2.0.1'});if(req.method==='GET'&&req.url==='/printers')return json(res,200,{printers:await listPrinters()});if(req.method==='POST'&&req.url==='/print'){const b=await body(req),result=await(queue=queue.then(()=>handlePrint(b),()=>handlePrint(b)));return json(res,200,result)}return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:e.message||'Print agent error'})}});server.listen(Number(config.port||17483),'127.0.0.1',()=>console.log(`Cocktaillo Print Agent running on 127.0.0.1:${config.port||17483}`));
