import {NextResponse} from 'next/server';
import {getUser,allow} from '../../../lib/auth.js';
import {mutateState} from '../../../lib/store.js';
const INSTAGRAM_URL='https://www.instagram.com/cocktaillorestocafe?igsi=MThhZmZ3MTVpMTF2bg==';
function receiptPayload(state,receipt){const table=receipt.table_id?state.tables.find(t=>t.id===receipt.table_id):null;const p=receipt.payment||{};const payment_method=Number(p.usd_cents||0)>0&&Number(p.lbp||0)>0?'USD + LBP':Number(p.lbp||0)>0?'LBP':'USD';return {business_name:'COCKTAILLO',order_number:receipt.number,receipt_id:receipt.id,order_id:receipt.order_id,type:receipt.type,table:table?.name||null,created_at:receipt.created_at,cashier:receipt.cashier,items:(receipt.items||[]).map(l=>({name:l.name_en,quantity:Number(l.quantity||1),unit_price_cents:Number(l.price_cents||0),line_total_cents:Number(l.price_cents||0)*Number(l.quantity||1),addons:(l.addons||[]).map(a=>({name:a.name_en,quantity:Number(a.quantity||1),price_lbp:Number(a.price_lbp||0)}))})),subtotal_cents:Number(receipt.totals?.subtotal_equivalent_cents??receipt.totals?.total_equivalent_cents??0),discount_cents:Number(receipt.totals?.discount_cents||0),total_cents:Number(receipt.totals?.total_equivalent_cents||0),payment_method,paid_usd_cents:Number(p.usd_cents||0),paid_lbp:Number(p.lbp||0),exchange_rate:Number(p.rate||state.settings.exchange_rate||89500),change_cents:Number(receipt.change_cents||0),footer:state.settings.receipt_footer||'',instagram_url:INSTAGRAM_URL,instagram_handle:'@cocktaillorestocafe'}}
function ticketPayload(state,job){const ticket=state.tickets.find(t=>t.id===job.ticket_id);if(!ticket)throw new Error('Bar ticket not found.');const table=ticket.table_id?state.tables.find(t=>t.id===ticket.table_id):null;return {id:ticket.id,order_id:ticket.order_id,order_number:ticket.order_number,table:table?.name||null,table_id:ticket.table_id||null,station:ticket.station,staff_name:ticket.staff_name,created_at:ticket.created_at,lines:ticket.lines||[]}}
export async function POST(request){const user=await getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});if(!allow(user,'cashier','manager'))return NextResponse.json({error:'Cashier access required.'},{status:403});const b=await request.json().catch(()=>({}));try{const out=await mutateState(state=>{state.print_jobs=Array.isArray(state.print_jobs)?state.print_jobs:[];const now=new Date().toISOString();
if(b.action==='claim-next'){const job=state.print_jobs.find(j=>j.destination==='bar'&&(j.status==='pending'||j.status==='failed'));if(!job)return {job:null};job.status='printing';job.updated_at=now;job.attempts=Number(job.attempts||0)+1;return {job,ticket:ticketPayload(state,job),printer_name:job.printer_name||state.settings.bar_printer_name||'Bar Printer'};}
if(b.action==='create'){const receipt=state.receipts.find(r=>r.id===b.receipt_id);if(!receipt)throw new Error('Paid receipt not found.');const mode=b.mode==='reprint'?'reprint':'automatic';if(mode==='automatic'){const existing=state.print_jobs.find(j=>j.receipt_id===receipt.id&&j.destination==='customer'&&j.mode==='automatic');if(existing)return {job:existing,receipt:receiptPayload(state,receipt),printer_name:state.settings.customer_printer_name||'Customer Receipt',should_print:existing.status!=='printed'&&existing.status!=='printing'}}const job={id:`print-${crypto.randomUUID()}`,receipt_id:receipt.id,order_id:receipt.order_id,order_number:receipt.number,destination:'customer',mode,status:'pending',printer_name:state.settings.customer_printer_name||'Customer Receipt',created_at:now,updated_at:now,attempts:0,last_error:null,printed_at:null,requested_by:user.name};state.print_jobs.push(job);state.audit.push({id:`audit-${crypto.randomUUID()}`,type:mode==='reprint'?'customer_receipt_reprint_queued':'customer_receipt_print_queued',order_id:receipt.order_id,print_job_id:job.id,user:user.name,at:now});return {job,receipt:receiptPayload(state,receipt),printer_name:job.printer_name,should_print:true}}
if(b.action==='status'){const job=state.print_jobs.find(j=>j.id===b.job_id);if(!job)throw new Error('Print job not found.');if(!['pending','printing','printed','failed'].includes(b.status))throw new Error('Invalid print status.');job.status=b.status;job.updated_at=now;if(b.status==='printing')job.attempts=Number(job.attempts||0)+1;if(b.status==='printed'){job.printed_at=now;job.last_error=null;state.audit.push({id:`audit-${crypto.randomUUID()}`,type:`${job.destination}_print_completed`,order_id:job.order_id,print_job_id:job.id,user:user.name,at:now})}if(b.status==='failed'){job.last_error=String(b.error||'Unknown printing error').slice(0,500);state.audit.push({id:`audit-${crypto.randomUUID()}`,type:`${job.destination}_print_failed`,order_id:job.order_id,print_job_id:job.id,user:user.name,at:now,reason:job.last_error})}return {job}}
if(b.action==='retry'){const job=state.print_jobs.find(j=>j.id===b.job_id);if(!job)throw new Error('Print job not found.');if(job.destination==='bar')return {job,ticket:ticketPayload(state,job),printer_name:job.printer_name||state.settings.bar_printer_name||'Bar Printer',should_print:job.status!=='printed'};const receipt=state.receipts.find(r=>r.id===job.receipt_id);if(!receipt)throw new Error('Receipt not found.');return {job,receipt:receiptPayload(state,receipt),printer_name:job.printer_name||state.settings.customer_printer_name||'Customer Receipt',should_print:job.status!=='printed'}}throw new Error('Unknown print job action.');});return NextResponse.json(out)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Print job failed.'},{status:400})}}
